### ISSUE TITLE
migration transition

### ISSUE THREAD

**Issue by aendeavor** [docker-mailserver/docker-mailserver#2]
This is the official tracking issue for the transition into the new repository in the new organization. Related discussions take place here.

---

#### Top Priority

- [x] Integrate GH Actions
- [x] Integrate a scheduled build for the `stable` branch

#### Medium Priority

- [x] Update the labelling (<https://github.com/opencontainers/image-spec/blob/master/annotations.md>)
- [x] Update the `Makefile`

**Comment by radicand** [comment]
Opened PR #3 to bring in Github Actions CI.

**Comment by aendeavor** [comment]
@radicand I have a question which you can probably easily answer for me:) I am currently re-working the labeling of the image to use the current standardized [OCI Image Spec Annotatios](https://github.com/opencontainers/image-spec/blob/master/annotations.md). Therefore, I would like to use

``` DOCKERFILE
LABEL org.opencontainers.image.created=${CREATED}
```

which is working perfectly, but I will need to integrate it into the CI too. Therefore, how do I go about this? This sectin the workflow and one other section like this need it:

``` YAML
      - name: Build image locally
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          build-args: |
            VCS_REF=${{ github.sha }}
            VCS_VERSION=${{ github.ref }}
            # HERE IS THE NEW ARG
            CREATED=`date -u +'%Y-%m-%dT%H:%M:%SZ'`
```

The date is formatted with the Bash command `date -u +'%Y-%m-%dT%H:%M:%SZ'`. How do I write that in the GH Actions?

**Comment by radicand** [comment]
We can use a process like mentioned at https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows#comment115875910_60942437 to generate a date and reference it later

**Comment by aendeavor** [comment]
> We can use a process like mentioned at https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows#comment115875910_60942437 to generate a date and reference it later

Yeah, that should work. I will tend to it when #3 is merged.

**Comment by casperklein** [comment]
Two additional things we should keep in mind:

- Copy over the old Wiki
- Update references (links etc.)

**Comment by aendeavor** [comment]
> Two additional things we should keep in mind:
> 
> 
> 
> - Copy over the old Wiki
> 
> - Update references (links etc.)

Very true, but we can do that gradually. The old wiki is still intact, and the links to these pages can stay as long as there are no new pages. Some parts of the wiki should be re-written, some can be copied.

But you're right. We will need to keep this in mind.
