### ISSUE TITLE
[FR] Implementing replication

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#2048]
# Feature Request

## Context

Replicate on multiple servers

### Is your Feature Request related to a Problem?

No

### Describe the Solution you'd like

Support for the feature

### Are you going to implement it?

Maybe

### What are you going to contribute??

Configs

### Alternatives you've considered

None

### Who will that Feature be useful to?

All users

### What have you done already?

Trying to config

**Comment by williamdes** [comment]
For now I am using the following links:
- https://www.swordarmor.fr/replication-mastermaster-entre-deux-serveurs-mail-avec-dovecot-dsync.html
- https://www.howtoforge.com/community/threads/use-dovecot-to-replicate-your-mails.66318/
- https://blog.schaal-24.de/ispconfig/mails-mit-dovecot-ueber-tcp-syncen/?lang=en

And had to add ([docs](https://doc.dovecot.org/configuration_manual/authentication/ldap_settings_auth/)):
```ini
iterate_filter = (objectClass=PostfixBookMailAccount)
iterate_attrs = mail=user
```
on `/etc/dovecot/dovecot-ldap.conf.ext` to have `doveadm user -u "*"` show me the user list

I will keep this updated as I progress to success

**Comment by williamdes** [comment]
Here is the full patch ([Source](https://github.com/desportes/infrastructure/blob/7134c8c819ffe8558f1a083835a2771cf65b429b/user-patches.sh))

 ```bash
#!/bin/bash

set -e

##
# This user script will be executed between configuration and starting daemons
# To enable it you must save it in your config directory as "user-patches.sh"
##
echo ">>>>>>>>>>>>>>>>>>>>>>>Applying patches<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

# ...
echo 'Enabling replication'

sed -i '/^iterate_filter =/d' /etc/dovecot/dovecot-ldap.conf.ext
sed -i '/^iterate_attrs =/d' /etc/dovecot/dovecot-ldap.conf.ext

printf '\niterate_filter = (objectClass=PostfixBookMailAccount)\n' >> /etc/dovecot/dovecot-ldap.conf.ext
printf '\niterate_attrs = mail=user\n' >> /etc/dovecot/dovecot-ldap.conf.ext

sed -i 's/^mail_plugins =.*/mail_plugins = \$mail_plugins notify replication/' /etc/dovecot/conf.d/10-mail.conf

cat <<EOF > /etc/dovecot/conf.d/10-replication.conf
service doveadm {
	inet_listener {
		port = 4177
		ssl = yes
	}
}
ssl = required
ssl_verify_client_cert = no
auth_ssl_require_client_cert = no
ssl_cert = <${SSL_CERT_PATH}
ssl_key = <${SSL_KEY_PATH}
ssl_client_ca_file = ${DOVECOT_TLS_CACERT_FILE}
ssl_client_ca_dir = /etc/ssl/certs/
doveadm_port = 4177
doveadm_password = ${DOVECOT_ADM_PASS}
service replicator {
	process_min_avail = 1
	unix_listener replicator-doveadm {
		mode = 0600
	}
}
service aggregator {
	fifo_listener replication-notify-fifo {
		user = dovecot
	}
	unix_listener replication-notify {
		user = dovecot
	}
}
EOF

# Check if configured
if [ -n "${DOVECOT_REPLICA_SERVER}" ]; then
    # Open the config
    sed -i '/^}/d' /etc/dovecot/conf.d/90-plugin.conf
    # Remove a possible old value of mail_replica
    sed -i '/^mail_replica/d' /etc/dovecot/conf.d/90-plugin.conf
    # Insert the config and close it back
    printf '\nmail_replica = tcps:%s\n}\n' "${DOVECOT_REPLICA_SERVER}" >> /etc/dovecot/conf.d/90-plugin.conf
fi

echo ">>>>>>>>>>>>>>>>>>>>>>>Finished applying patches<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
```

**Comment by williamdes** [comment]
new ENVs
```
DOVECOT_ADM_PASS=randomPassWordChangeMe
DOVECOT_REPLICA_SERVER=hostThatValidatesOnSslCertFQDN
```

new port: 4177

commands:
```
docker exec -it desportesemail_mailserver_1 doveadm replicator status
# Force sync, start on empty server
docker exec -it desportesemail_mailserver_1 doveadm -v sync -A -d
docker exec -it desportesemail_mailserver_1 doveadm replicator status
```

Set DOVECOT_REPLICA_SERVER empty on the main server, until the replica server is filled up with data
Then set DOVECOT_REPLICA_SERVER on the main to the replica address and force sync and check status

**Comment by williamdes** [comment]
The config I posted works flawlessly since then, I am not sure how to make a PR to add the changes
Or maybe just make a page with the patch ?

**Comment by casperklein** [comment]
It's up to you 😃. If you think, a broader audience will benefit from that, implement it in full with ENVs etc.

If you think, only a small group will use that feature and it's not worth to implement it directly in DMS, just write a doc page 👍

You can take a look at old issues, to see if there is demand. I can't remember, that this feature was ever requested by someone.

**Comment by polarathene** [comment]
There doesn't appear to be much interest or demand for this feature?

I don't mind leaving it open, but I get the impression it's just going to build up a constant stream of stale bot ping pong for an indeterminate amount of time (I can add the ignore label to prevent that if desired).

Probably safe to assume at this point that @williamdes can:

- Contribute a feature PR (but it is unclear when he'll have time to do so, or if is still interested in doing so).
- Contribute an example with snippets/instructions shared above in this issue thread to the docs to make it more discoverable.
- Contribute a FAQ entry about replication and linking the users to this issue as reference for discovery.
- Close the issue. Any other users in future seeking this support may discover this issue and express renewed interest in picking it up instead.

There's no pressure to contribute, we all get busy and lack time to work on all the tasks we originally set out to do. If you would still like to see this through, let me know, but it's totally ok to not worry about it and close too :+1:

**Comment by polarathene** [comment]
The Dovecot LDAP config file is modified by any env that is prefixed with `DOVECOT_` followed by the key name in the config file (all uppercase). For example you should be able to use `DOVECOT_ITERATE_FILTER: "(objectClass=PostfixBookMailAccount)"` in your `compose.yaml` ENV section.

https://github.com/docker-mailserver/docker-mailserver/blob/86e18d04ddf6b39f33a36e2fd5d8b388265656de/target/scripts/startup/setup.d/ldap.sh#L34-L60

That has some special handling but the relevant part here is calling this utility function to update the config file:

https://github.com/docker-mailserver/docker-mailserver/blob/86e18d04ddf6b39f33a36e2fd5d8b388265656de/target/scripts/helpers/utils.sh#L88

It doesn't look like the utility currently supports adding entries that don't exist yet (_[relevant test](https://github.com/docker-mailserver/docker-mailserver/blob/master/test/tests/parallel/set3/scripts/replace_by_env_in_file.bats)_), so you'd still need to include `iterate_filter` + `iterate_attrs` anyway.

---

For now the easiest way for you would be to use `user-patches.sh`.

Maybe you could open a PR that:
- Adds the two Dovecot LDAP keys with empty/default values to [this file](https://github.com/docker-mailserver/docker-mailserver/blob/86e18d04ddf6b39f33a36e2fd5d8b388265656de/target/dovecot/dovecot-ldap.conf.ext).
- Support the other requirement (`mail_plugins`), you could [add a feature function for Dovecot replication support in this file](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/startup/setup.d/dovecot.sh) and [call it from here](https://github.com/docker-mailserver/docker-mailserver/blob/86e18d04ddf6b39f33a36e2fd5d8b388265656de/target/scripts/start-mailserver.sh#L45-L50).
- Small docs addition to enable the feature and brief reference to the related config (`iterate_filter` + `iterate_attrs`), which if it makes sense to could have default values used when enabling the feature (_if they're generic enough_), then it can be under a single ENV toggle (_[belongs here](https://github.com/docker-mailserver/docker-mailserver/blob/86e18d04ddf6b39f33a36e2fd5d8b388265656de/target/scripts/startup/variables-stack.sh#L66-L87)_).
- The tricky part is probably how to write a test for it. We have refactored our test suite, you could copy/paste most of what you see in [this Dovecot test](https://github.com/docker-mailserver/docker-mailserver/blob/86e18d04ddf6b39f33a36e2fd5d8b388265656de/test/tests/parallel/set1/dovecot/mailbox_format_dbox.bats) and adjust it to test replication is working well (_but I imagine that's a bit more complicated to setup and test properly?_).

The test is likely going to be your blocker, even for maintainers as we're all low on time ourselves and I don't think any are familiar with the replication feature (_which seems to require a fair bit more configuration from your earlier links_).

---

Is there an issue with relying on `user-patches.sh`? Since you opened this feature request, no other user has expressed interest in wanting it.

Maintainers aren't fond of adopting the burden of maintenance for features they don't use and has a small audience. When that is the case, we prefer to advise `user-patches.sh` or extending our image with your own `Dockerfile`, or contributing to our docs for the benefit of others.

**Comment by 501st-alpha1** [comment]
> ... no other user has expressed interest ...

Since you mention this, I'll mention that I am interested in replication, and have been subscribed to this issue for a while.  I've had other more pressing priorities that have prevented me from experimenting with this myself, but I am interested in using this as a means to improve my site-level redundancy.

> Maintainers aren't fond of adopting the burden of maintenance for features they don't use and has a small audience. When that is the case, we prefer to advise `user-patches.sh` or extending our image with your own `Dockerfile`, or contributing to our docs for the benefit of others.

I definitely understand this concern; I'm not familiar enough to know what the best solution would be, but I see no problem using `user-patches.sh` or extending a new Docker image.

**Comment by polarathene** [comment]
> I am interested in replication, and have been subscribed to this issue for a while.

Then I would advise you and anyone else subscribed to :+1: the feature request as that helps communicate it. We can't see that others are subscribed to the issue :sweat_smile: 

If there is more it helps towards the other maintainers approving a PR that implements the support.

**Comment by 501st-alpha1** [comment]
> Then I would advise you and anyone else subscribed to :+1: the feature request as that helps communicate it. We can't see that others are subscribed to the issue :sweat_smile:

Done; I normally always do this, but I must have forgotten to do that here for some reason. 😳

**Comment by vaskozl** [comment]
@williamdes thanks for providing the user-patches.sh! I'm now using a [variant](https://github.com/vaskozl/home-infra/blob/main/cluster/mail/config/user-patches.sh) of it to achieve HA on my personal setup.

Some suggestions to improve it, with the context of potential officiall support.
* There is no reason to try to potentially incorrectly sed around the curly braces on `90-plugin.conf` when you can just include the plugin directly in `10-replication.conf` an keep it self contained
* The iterate_* lines are LDAP specific and should be in a separate config or ENV vars. They are not necessary if not using LDAP. Instead the docs should indicate setting the env vars like polathene suggested. For mysql you'd need `iterate_query`.
* Use `sed -i '/^mail_plugins =/ s/$/ notify replication/' /etc/dovecot/conf.d/10-mail.conf` so as to only append to mail_plugins instead of replacing the whole line, otherwise you could also use a capture group.
* I would think the replication is not higher priority than setting up mailboxes, as such I would probably use 30 or more for the start of the filename, e.g. 30-replication.conf
* Nitpick, but line indentations could be aligned and not a mix of tabs and spaces

**Comment by williamdes** [comment]
Here is the new version of my patch: https://github.com/docker-mailserver/docker-mailserver/issues/2048#issuecomment-865305071

- [x] There is no reason to try to potentially incorrectly sed around the curly braces on 90-plugin.conf when you can just include the plugin directly in 10-replication.conf an keep it self contained

- [ ] The iterate_* lines are LDAP specific and should be in a separate config or ENV vars. They are not necessary if not using LDAP. Instead the docs should indicate setting the env vars like polathene suggested. For mysql you'd need iterate_query.

I need to check, the doveadm commands did seem to need it while I tested this

- [x] Use sed -i '/^mail_plugins =/ s/$/ notify replication/' /etc/dovecot/conf.d/10-mail.conf so as to only append to mail_plugins instead of replacing the whole line, otherwise you could also use a capture group.

- [ ] I would think the replication is not higher priority than setting up mailboxes, as such I would probably use 30 or more for the start of the filename, e.g. 30-replication.conf

Not a big deal, for me replication is a top priority. But I am open to change that

- [x] Nitpick, but line indentations could be aligned and not a mix of tabs and spaces

**Comment by MohammedNoureldin** [comment]
Hi @williamdes,

I know that you have quite a lot of work here. But don't you think that we should invest some time to implement the `director` approach rather than replication? Replication is fine and helpful, but the directory approach is the one that is really scalable.

I may help if you plan to implement it with me.

**Comment by shierro** [comment]
Hi, I also landed here because I can see from dovecot official docs mentioned [here](https://doc.dovecot.org/admin_manual/director/dovecotdirector/#:~:text=Dovecot%20Director%20is%20that%20the%20director%20makes%20sure%20that%20a%20single%20user%20is%20never%20accessed%20by%20different%20backends%20at%20the%20same%20time) that the director is "_needed to keep the performance good and to avoid potential problems_". I haven't seen its implementation in DMS though. In your experience with DMS, have you not encountered issues without the director, and has someone had success with multi-node clustering in k8s? thanks for your inputs in advance and apologies if asking in a wrong thread

**Comment by polarathene** [comment]
> In your experience with DMS, have you not encountered issues without the director, and has someone had success with multi-node clustering in k8s? thanks for your inputs in advance and apologies if asking in a wrong thread

The issue author has since migrated to Stalwart (rust-based alternative).

I don't have any input regarding k8s or clusters/replication. It's probably most likely to suit k8s deployments and thus the community / discussion for such may be better suited over at the `docker-mailserver-helm` repo?

---

In the meantime, the DMS community is advised to contribute to our docs advice for this support. Presently over the span of 3 years, the feature request has only garnered 6 👍 total. The demand is rather low.

No maintainers have interest in tackling this AFAIK. I'm not sure how many users of DMS actually need such support (beyond nice to have). If you need to operate a mailserver at a larger scale, alternative projects are likely more suitable for your needs?
