### ISSUE TITLE
tracking: `rspamd`

### ISSUE THREAD

**Issue by georglauterbach** [docker-mailserver/docker-mailserver#2739]
# Note

This is the tracking issue for the implementation of `Rspamd`. Amavis/SA will continue to exist in DMS for now.

---

# Tracking

## Open Tasks

- [x] reach agreement among maintainers (see the [related discussion](https://github.com/orgs/docker-mailserver/teams/maintainers/discussions/52))
- [x] start with the implementation
- [x] clean up the `Dockerfile`
- [x] provide sane default configuration files
- [x] provide easy setup experience
- [x] provide easy configuration of modules (see #3059)
- [ ] monitor current integration for issues & bugs (in progress)
- [ ] receive comminity feedback (in progress)

## Pull Requests

- #2902
- #3016
- #3039
- #3059

**Comment by georglauterbach** [comment]
First of 3, #2903 was merged.

**Comment by georglauterbach** [comment]
upcoming next: #3016

**Comment by georglauterbach** [comment]
Second of three, #3016 was merged.

NOTE: A small follow-up PR is currently in review phase (#3026), but not strictly required to get Rspamd working.

---

With #3016, we reached a level of support for this feature that I can comfortably say that anyone who wants to give Rspamd a try should definitely do it. We continue supporting Amavis/SA for the time being though, so no worries!

**Comment by georglauterbach** [comment]
#3059 should finalize the preliminary setup of Rspamd. We are going to keep it as experimental for v12.0.0. I would like to get some community feedback. With #3059 merged, the docs are updated, saying that Rspamd integration will be stabilized with v12.1.0. Hence I am going to assign this issue to the correct milestone now.

**Comment by georglauterbach** [comment]
#3059 is now merged

**Comment by georglauterbach** [comment]
I will close this as the [Rspamd Project Page](https://github.com/orgs/docker-mailserver/projects/3/views/1) will now track the integration status.
