### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by joseraeiro** [docker-mailserver/docker-mailserver#2751]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

mailserver/docker-mailserver

### What happened and when does this occur?

```Markdown
I can't send an email to gmail using winprovit.pt as my domainname
```

### What did you expect to happen?

```Markdown
I expected that the email would be sent.
```

### How do we replicate the issue?

```Markdown
1. Installed mailserver using docker-compose as per instructions
2. Added a user using ./setup.sh email add <user@domain>
3. Tried to use GoPhish to send an email to gmail, using its test function after having configured SMTP server correctly (Gophish states that it sends the email)
...
```

### DMS version

v10.1.2

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
services:

  mailserver:

    image: docker.io/mailserver/docker-mailserver:latest

    container_name: mailserver

    # If the FQDN for your mail-server is only two labels (eg: example.com),

    # you can assign this entirely to `hostname` and remove `domainname`.

    hostname: mail

    domainname: winprovit.pt

    env_file: mailserver.env

    # More information about the mail-server ports:

    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/

    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.

    ports:

      - "25:25"    # SMTP  (explicit TLS => STARTTLS)

      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)

      - "465:465"  # ESMTP (implicit TLS)

      - "587:587"  # ESMTP (explicit TLS => STARTTLS)

      - "993:993"  # IMAP4 (implicit TLS)

    volumes:

      - ./docker-data/dms/mail-data/:/var/mail/

      - ./docker-data/dms/mail-state/:/var/mail-state/

      - ./docker-data/dms/mail-logs/:/var/log/mail/

      - ./docker-data/dms/config/:/tmp/docker-mailserver/

      - /etc/localtime:/etc/localtime:ro

    restart: always

    stop_grace_period: 1m

    cap_add:

      - NET_ADMIN

    healthcheck:

      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"

      timeout: 3s

      retries: 0
```

### Relevant log output

```bash
Now follows the output from docker logs:

Aug 29 11:35:10 mail postfix/postscreen[2558]: CONNECT from [172.23.0.1]:51738 to [172.23.0.2]:25

Aug 29 11:35:16 mail postfix/postscreen[2558]: PASS NEW [172.23.0.1]:51738

Aug 29 11:35:16 mail postfix/smtpd[2576]: warning: hostname jose-VirtualBox does not resolve to address 172.23.0.1

Aug 29 11:35:16 mail postfix/smtpd[2576]: connect from unknown[172.23.0.1]

Aug 29 11:35:16 mail postfix/smtpd[2576]: warning: connect to Milter service inet:localhost:8891: Cannot assign requested address

Aug 29 11:35:16 mail postfix/smtpd[2576]: 3A07F2005C6: client=unknown[172.23.0.1], sasl_method=PLAIN, sasl_username=teste@winprovit.pt

Aug 29 11:35:16 mail postfix/cleanup[2490]: 3A07F2005C6: message-id=<>

Aug 29 11:35:16 mail postfix/qmgr[2467]: 3A07F2005C6: from=<teste@winprovit.pt>, size=757, nrcpt=1 (queue active)

Aug 29 11:35:16 mail postfix/smtpd[2576]: disconnect from unknown[172.23.0.1] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6

Aug 29 11:35:16 mail postfix/smtpd-amavis/smtpd[2582]: connect from localhost[127.0.0.1]

Aug 29 11:35:16 mail postfix/smtpd-amavis/smtpd[2582]: 52F932005EE: client=localhost[127.0.0.1]

Aug 29 11:35:16 mail postfix/cleanup[2492]: 52F932005EE: message-id=<20220829103516.52F932005EE@mail.winprovit.pt>

Aug 29 11:35:16 mail postfix/qmgr[2467]: 52F932005EE: from=<teste@winprovit.pt>, size=976, nrcpt=1 (queue active)

Aug 29 11:35:16 mail amavis[1580]: (01580-01) Passed CLEAN {RelayedOpenRelay}, [172.23.0.1]:51738 <teste@winprovit.pt> -> <joseraeiro@gmail.com>, Queue-ID: 3A07F2005C6, mail_id: KAHH4b1Hs38Y, Hits: -, size: 704, queued_as: 52F932005EE, 86 ms

Aug 29 11:35:16 mail postfix/smtp-amavis/smtp[2580]: 3A07F2005C6: to=<joseraeiro@gmail.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.13, delays=0.01/0.02/0.01/0.1, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 52F932005EE)

Aug 29 11:35:16 mail postfix/qmgr[2467]: 3A07F2005C6: removed

Aug 29 11:35:16 mail postfix/smtp[2584]: 52F932005EE: to=<joseraeiro@gmail.com>, relay=gmail-smtp-in.l.google.com[108.177.126.27]:25, delay=0.42, delays=0.01/0.04/0.2/0.17, dsn=5.7.26, status=bounced (host gmail-smtp-in.l.google.com[108.177.126.27] said: 550-5.7.26 The MAIL FROM domain [winprovit.pt] has an SPF record with a hard 550-5.7.26 fail policy (-all) but it fails to pass SPF checks with the ip: 550-5.7.26 [62.28.250.46]. To best protect our users from spam and phishing, 550-5.7.26 the message has been blocked. Please visit 550-5.7.26  https://support.google.com/mail/answer/81126#authentication for more 550 5.7.26 information. p31-20020a056402501f00b0043bb6a22af3si6645250eda.387 - gsmtp (in reply to end of DATA command))

Aug 29 11:35:16 mail postfix/cleanup[2490]: BD9552005EF: message-id=<20220829103516.BD9552005EF@mail.winprovit.pt>

Aug 29 11:35:16 mail postfix/qmgr[2467]: BD9552005EF: from=<>, size=3851, nrcpt=1 (queue active)

Aug 29 11:35:16 mail postfix/bounce[2488]: 52F932005EE: sender non-delivery notification: BD9552005EF

Aug 29 11:35:16 mail postfix/qmgr[2467]: 52F932005EE: removed

Aug 29 11:35:16 mail dovecot: lmtp(2479): Connect from local

Aug 29 11:35:16 mail dovecot: lmtp(teste@winprovit.pt)<2479><mFyHLmSWDGOvCQAApC8tBw>: sieve: msgid=<20220829103516.BD9552005EF@mail.winprovit.pt>: stored mail into mailbox 'INBOX'

Aug 29 11:35:16 mail postfix/lmtp[2472]: BD9552005EF: to=<teste@winprovit.pt>, relay=mail.winprovit.pt[/var/run/dovecot/lmtp], delay=0.03, delays=0/0/0/0.02, dsn=2.0.0, status=sent (250 2.0.0 <teste@winprovit.pt> mFyHLmSWDGOvCQAApC8tBw Saved)

Aug 29 11:35:16 mail postfix/qmgr[2467]: BD9552005EF: removed

Aug 29 11:35:16 mail dovecot: lmtp(2479): Disconnect from local: Client has quit the connection (state=READY)
```

### What level of experience do you have with Docker and mail servers?

- [X] I am inexperienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
As the log states, your DNS SPF record is not correct:

`Aug 29 11:35:16 mail postfix/smtp[2584]: 52F932005EE: to=<joseraeiro@gmail.com>, relay=gmail-smtp-in.l.google.com[108.177.126.27]:25, delay=0.42, delays=0.01/0.04/0.2/0.17, dsn=5.7.26, status=bounced (host gmail-smtp-in.l.google.com[108.177.126.27] said: 550-5.7.26 The MAIL FROM domain [winprovit.pt] has an SPF record with a hard 550-5.7.26 fail policy (-all) but it fails to pass SPF checks with the ip: 550-5.7.26 [62.28.250.46]. To best protect our users from spam and phishing, 550-5.7.26 the message has been blocked. Please visit 550-5.7.26  https://support.google.com/mail/answer/81126#authentication for more 550 5.7.26 information. p31-20020a056402501f00b0043bb6a22af3si6645250eda.387 - gsmtp (in reply to end of DATA command))`

`62.28.250.46` (your mailserver IP address) must be included in the SPF record.

**Comment by joseraeiro** [comment]
And how can I accomplish that? Editing the DNS records of my domain? What should I have to add in there?

Sorry for the question, but I'm an unexperienced user regarding SMTP configurations...

**Comment by georglauterbach** [comment]
Moreover, I see

``` TXT
warning: connect to Milter service inet:localhost:8891: Cannot assign requested address
```

OpenDKIM does not seem to run properly too.

**Comment by joseraeiro** [comment]
> Moreover, I see
> 
> ```
> warning: connect to Milter service inet:localhost:8891: Cannot assign requested address
> ```
> 
> OpenDKIM does not seem to run properly too.

And what would require to make Open DKIM to run properly?

> 
> > Sorry for the question, but I'm an unexperienced user regarding SMTP configurations...
> 
> There are countless guides on the internet. Please try to use them :)

Will do! I'm googling as we speak, but I'm unable to find out what to put in the Name section of the DNS record.

**Comment by joseraeiro** [comment]
> This project has a very good [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) about all the aspects of the mailserver.
> 
> You can find all the informations about what you asked before (setting up [SPF](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/spf/) and [DKIM](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/dkim/)).
> 
> You said you are inexperienced with mailservers. I would strongly advice to check the [basic overview](https://docker-mailserver.github.io/docker-mailserver/edge/introduction/) and make yourself comfortable. Also, reading some additional articles, howtos, etc. will help. Running your own mailserver can be a bit tricky sometimes, the more you learn about the basics and read documentations, the easier it will be.

Thank you very much for all this information! I'll be sure to check the documentation!

**Comment by polarathene** [comment]
Also, our docs can sometimes be a bit rough. If you later have an "aha!" moment and notice a way we could better explain something to mail-server beginners, let us know - or even make a small contribution! (it's all just markdown) :grinning:

**Comment by joseraeiro** [comment]
> Also, our docs can sometimes be a bit rough. If you later have an "aha!" moment and notice a way we could better explain something to mail-server beginners, let us know - or even make a small contribution! (it's all just markdown) 😀

Of course. Count on me to do so.
