### ISSUE TITLE
[BUG] Building via Dockerfile fails

### ISSUE THREAD

**Issue by cryopie** [docker-mailserver/docker-mailserver#2905]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Docker build

### What happened and when does this occur?

```Markdown
Docker build fails.
```

### What did you expect to happen?

```Markdown
Docker image to be built successfully. It worked fine in 11.0.
```

### How do we replicate the issue?

```Markdown
Docker complains about the Dockerfile format


$ git clone https://github.com/docker-mailserver/docker-mailserver.git
$ git rev-parse HEAD
2bc4078e351bc6f3867524e38d0b5c578b107fb5

$ docker build .
Sending build context to Docker daemon  389.6kB
Error response from daemon: dockerfile parse error line 35: unknown instruction: ECHO

$ docker -v
Docker version 20.10.19, build d85ef84533
```

### DMS version

v11.2.0

### What operating system is DMS running on?

Linux

### Which operating system version?

Arch Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
`DOCKER_BUILDKIT=1 docker build .`
