### ISSUE TITLE
[BUG]: File permissions changed after restart

### ISSUE THREAD

**Issue by k7faq** [docker-mailserver/docker-mailserver#2906]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

File permissions

### What happened and when does this occur?

```Markdown
In testing my server I encountered the below issue after a server reboot. 
Here is the raw error encountered in my docker logs:


Nov 19 22:21:43 e08f0aeef7a0 dovecot: imap(nospam@dustyconsulting.com)<1297><tbGdIdrtPdVMf4sx>: Error: stat(/var/mail/dustyconsulting.com/nospam/.Notes/tmp) failed: Permission denied (euid=5000(docker) egid=5000(docker) missing +x perm: /var/mail, dir owner missing perms)


to resolve the above error I ran `docker exec -it mailserver chmod -R +x /var/mail`.
```

### What did you expect to happen?

```Markdown
The permissions of the filesystem within the container should not be able to be impacted by stoping the container and then starting it up again. Thus my rebooting my server should have not led me to this level of an issue.
```

### How do we replicate the issue?

```Markdown
Either 
1. docker stop mailserver
2. wait for the process to complete
3. docker start mailserver

OR 
1. reboot your server.

Version? As of 2022 Nov 19

 docker images
REPOSITORY                     TAG       IMAGE ID       CREATED         SIZE
mailserver/docker-mailserver   latest    aa627ef9c47f   5 weeks ago     562MB
```

### DMS version

latest - 11.2?

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian 11

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
version: '3.3'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    domainname: dustyconsulting.com 
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /srv/mailserver/mail-data/:/var/mail/
      - /srv/mailserver/mail-state/:/var/mail-state/
      - /srv/mailserver/mail-logs/:/var/log/mail/
      - /srv/mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /srv/mailserver/certbot/certs/:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```bash
Nov 19 22:21:43 e08f0aeef7a0 dovecot: imap(nospam@dustyconsulting.com)<1297><tbGdIdrtPdVMf4sx>: Error: stat(/var/mail/dustyconsulting.com/nospam/.Notes/tmp) failed: Permission denied (euid=5000(docker) egid=5000(docker) missing +x perm: /var/mail, dir owner missing perms)


NOTE: Above repeats for all folders associated with the email address/account.
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [X] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by polarathene** [comment]
Curious... why have you configured your container with `domainname: dustyconsulting.com` and no `hostname`? The comments right above it explicitly encourage you to use `hostname: dustyconsulting.com`.

I would expect this issue to be more commonly reported as it should affect everyone otherwise? There must be something about your setup that is configured differently?

We do have a startup script that performs a `chown -R` (without the `+x` though) here:

https://github.com/docker-mailserver/docker-mailserver/blob/2bc4078e351bc6f3867524e38d0b5c578b107fb5/target/scripts/helpers/utils.sh#L22-L36

Some maintainers do run DMS on Debian too and may be able to investigate if they can reproduce this. For the time being, you may want to workaround this with a [`user-patches.sh` script](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/).

**Comment by polarathene** [comment]
User has not responded to questions, closing due to lack of information.

**Comment by polarathene** [comment]
> Initially folders are setup correctly, i.e., ownership is based on OpenLDAP information (i.e., uid and gid). However, after a container restart the ownership of directories in `/var/mail` in the mounted persistent volume claim (PVC) are changed to 5000:5000

This sounds like https://github.com/docker-mailserver/docker-mailserver/pull/2256#issuecomment-1520978521

Known issue, but wasn't resolved by anyone affected in a compatible way.
