### ISSUE TITLE
[BUG] Weird but semi-consistent test failures

### ISSUE THREAD

**Issue by georglauterbach** [docker-mailserver/docker-mailserver#2966]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

CI

### What happened and when does this occur?

```Markdown
Not sure when it started exactly, but as of now, serial tests in `test/tests/serial/tests.bats` do not run (sometimes), because the setup procedure fails.
```

### What did you expect to happen?

```Markdown
I expected the tests to succeed as there is nothing that should prevent them from succeeding.
```

### How do we replicate the issue?

```Markdown
1. Open a PR
2. Watch how the tests for this PR fail sporadically

or

1. Merge a PR
2. Watch how the tests on `master` fail
```

### DMS version

v11.3.1

### What operating system is DMS running on?

Linux

### Which operating system version?

Ubuntu 22.04

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
N/A
```

### Relevant log output

```bash
not ok 212 setup_file failed
# (from function `repeat_until_success_or_timeout' in file test/test_helper/common.bash, line 43,
#  from function `wait_until_change_detection_event_completes' in file test/test_helper/common.bash, line 208,
#  from function `setup_file' in test file test/tests/serial/tests.bats, line 50)
#   `wait_until_change_detection_event_completes mail' failed
# 8d7ce2717447a5b330bc24466c6b6b3110fff825af10b80fbc0248287fa3372d
# [   INF   ]  mail.my-domain.com is up and running
# Timed out on command: __is_changedetector_processing
# mail
# bats warning: Executed 212 instead of expected 309 tests
make: *** [Makefile:52: tests/serial] Error 1
Error: Process completed with exit code 2.
```

### Other relevant information

An example failure can be seen via the following link: <https://github.com/docker-mailserver/docker-mailserver/actions/runs/3789635420/jobs/6443579882#step:5:219>

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by polarathene** [comment]
Likely a race condition that was noted [here](https://github.com/docker-mailserver/docker-mailserver/pull/2947#issuecomment-1363541724):

> > `postfix/master.*: reload -- version .*, configuration /etc/postfix`
> > `dovecot: master: Warning: SIGHUP received - reloading configuration`
> 
> These seem to appear in the main logs via `docker logs <container name>`. Mentioning if we do get a need to match on that.
> 
> I guess this PR is fine now (_assuming the CI is a tad slower to avoid race condition_).

The failures I've seen recently have always been related to the functionality change here.

Technically a **false positive, as the change detection is just occurring too fast** during tests to catch a change event that starts and completes inbetween the 1 second polling window that the **current detection code is blind to it**.
