### ISSUE TITLE
[BUG] postfix: reject_unknown_client_hostname prevents legitimate mail from being received

### ISSUE THREAD

**Issue by mpldr** [docker-mailserver/docker-mailserver#2970]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postfix

### What happened and when does this occur?

```Markdown
mailserver  | Jan  1 12:35:19 mail postfix/smtpd[1556]: NOQUEUE: reject: RCPT from unknown[54.240.85.218]: 450 4.7.25 Client host rejected: cannot find your hostname, [54.240.85.218]; from=<010101856d1d37d3-cb9c308b-0000-0000-0000-a21593c7994e-000000@bounce.stripe.com> to=<my-localpart+stripe@example.com> proto=ESMTP helo=<a85-218.smtp-out.us-west-2.amazonses.com>
```
```


### What did you expect to happen?

```Markdown
I expected an option to turn `reject_unknown_client_hostname` off, if it is not considered necessary. I can overwrite the config in the docker-compose, but that feels hacky.
```

### How do we replicate the issue?

```Markdown
I have absolutely no idea. I don't think this happens for all SES mails.
```

### DMS version

latest (d5db200744f1)

### What operating system is DMS running on?

Linux

### Which operating system version?

Archlinux

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
moritz@pan ❯ cat docker-compose.yml                                 docker-mailserver -> master + ? ! $
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
      #entrypoint: ["/bin/sh", "-c", "while true; do sleep 10; done"]
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: moritz.sh
    env_file: mailserver.env
    network_mode: host
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "4190:4190" # MANAGE SIEVE
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./config/:/tmp/docker-mailserver/
      - ./docker-data/dms/config/dovecot/fts-xapian-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```bash
mailserver  | Jan  1 12:35:19 mail postfix/smtpd[1556]: NOQUEUE: reject: RCPT from unknown[54.240.85.218]: 450 4.7.25 Client host rejected: cannot find your hostname, [54.240.85.218]; from=<010101856d1d37d3-cb9c308b-0000-0000-0000-a21593c7994e-000000@bounce.stripe.com> to=<my-localpart+stripe@example.com> proto=ESMTP helo=<a85-218.smtp-out.us-west-2.amazonses.com>
```
```


### Other relevant information

_No response_

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

_No response_

**Comment by casperklein** [comment]
`54.240.85.218` resolves fine for me to `a85-218.smtp-out.us-west-2.amazonses.com`.

Does this work inside your container:

```
apt update
apt install bind9-dnsutils

dig -x 54.240.85.218
```

**Comment by mpldr** [comment]
It does

**Comment by casperklein** [comment]
Sorry, I've no further ideas. Does it happens for all mails?

**Comment by mpldr** [comment]
No, just stripe as far as I can see. For now I have disabled it by overwriting the main postfix config file in the container, but that's not a great solution.

**Comment by casperklein** [comment]
Alternatively, you can also use [user-patches.sh](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) for that:

`postconf 'smtpd_sender_restrictions = reject_authenticated_sender_login_mismatch, permit_sasl_authenticated, permit_mynetworks, reject_unknown_sender_domain'`

In my setup, it works as expected and only obvious Spam is rejected:

```
Jan  1 19:25:47 mail postfix/smtpd[470]: NOQUEUE: reject: RCPT from unknown[46.30.203.68] 450 4.7.25 Client host rejected: cannot find your hostname, [46.30.203.68]; from=<www-data@roundcube.hhu.de> to=<user@mydomain.tld> proto=ESMTP helo=<roundcube.hhu.de>
Jan  3 19:32:07 mail postfix/smtpd[31810]: NOQUEUE: reject: RCPT from unknown[185.176.220.152] 450 4.7.25 Client host rejected: cannot find your hostname, [185.176.220.152]; from=<codafe@furg.br> to=<user@mydomain.tld> proto=ESMTP helo=<46.30.190.16>
```

My best guess would be, that there are at least temporary DNS issues in your setup.

**Comment by N1k145** [comment]
Hi, I see the same issue with my setup, I tried the same test as @casperklein described, and all hostnames resolve fine for me. I also have this issue for local mails, that are sent and received on the same mail server. 

```
version: '3'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mx
    domainname: <domainname>
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
    #  - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/config/dovecot/10-mail.conf:/etc/dovecot/conf.d/10-mail.conf
      - ./docker-data/dms/config/dovecot/90-sieve-extprograms.conf:/etc/dovecot/conf.d/90-sieve-extprograms.conf
      - ./docker-data/dms/config/dovecot/90-sieve.conf:/etc/dovecot/conf.d/90-sieve.conf
      - ./push.sh:/usr/lib/dovecot/sieve-execute/push.sh

      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt/:/certs/
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - mailserver

networks:
  mailserver:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: <public IPv6 subnet>/64
         gateway: <public IPv6 addres>
```


I already disabled the rejection in my postfix-main.cf.
But I still see the warning messages in my log. So it's not an issue, but I can reproduce the issue from @mpldr

**Comment by casperklein** [comment]
@N1k145 Your issue might be [IPv6 related](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/ipv6/).

Do you see private IP addresses in your logs, when this happens?

**Comment by N1k145** [comment]
@casperklein No, I see the public IPs. I have the issue with IPv4 and IPv6 addresses. (My own is an IPv6, others are IPv4)

**Comment by casperklein** [comment]
I just re-read your post.

> I also have this issue for local mails, that are sent and received on the same mail server.

> No, I see the public IPs

You see public IP addresses for local mails??

**Comment by N1k145** [comment]
Sorry, for normal local mails I only see the IP of the client, but that's not the issue here.

The exact case is that I have ossec running on the same host, that sends email notifications from user1@domain to user2@domian.
As ossec does not support authorization for mails I configured postfix with permit_mynetworks and defined my public IPv6 address as "mynetworks". So ossec sends a mail to my mailserver from the same host, and then I see the public v6 address in the logs. 

I see the same message with my public IP when I send a mail from my Roundcube instance, also hosted on the same machine
Logs from a Roundcube mail:
```
Jan  4 15:12:30 mx postfix/submission/smtpd[59850]: warning: hostname mx.domain does not resolve to address <External IPv6 Address>
Jan  4 15:12:30 mx postfix/submission/smtpd[59850]: connect from unknown[<External IPv6 Address>]
Jan  4 15:12:30 mx postfix/submission/smtpd[59850]: Anonymous TLS connection established from unknown[<External IPv6 Address>]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
Jan  4 15:12:30 mx postfix/submission/smtpd[59850]: 4F63E260907: client=unknown[<External IPv6 Address>], sasl_method=LOGIN, sasl_username=sender@domain
Jan  4 15:12:30 mx postfix/sender-cleanup/cleanup[60005]: 4F63E260907: replace: header MIME-Version: 1.0 from unknown[<External IPv6 Address>]; from=<sender@domain> to=<reciever@domain> proto=ESMTP helo=<roundcube.domain>: Mime-Version: 1.0
Jan  4 15:12:30 mx postfix/sender-cleanup/cleanup[60005]: 4F63E260907: message-id=<e97e476d070706773bd36869a5de0847@domain>
Jan  4 15:12:30 mx opendkim[1150]: 4F63E260907: DKIM-Signature field added (s=mail, d=domain)
Jan  4 15:12:30 mx postfix/qmgr[1887]: 4F63E260907: from=<sender@domain>, size=365, nrcpt=1 (queue active)
Jan  4 15:12:30 mx postfix/submission/smtpd[59850]: disconnect from unknown[<External IPv6 Address>] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Jan  4 15:12:30 mx dovecot: imap-login: Login: user=<sender@domain>, method=PLAIN, rip=<External IPv6 Address>, lip=2001:3984:3989::2, mpid=60304, TLS, session=<cAVgxnDxLI8qAsIGMAkyEwAAAAAAAAAB>
Jan  4 15:12:30 mx dovecot: imap(sender@domain)<60304><cAVgxnDxLI8qAsIGMAkyEwAAAAAAAAAB>: Logged out in=414 out=747 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan  4 15:12:31 mx postfix/smtpd-amavis/smtpd[60011]: connect from localhost[127.0.0.1]
Jan  4 15:12:31 mx postfix/smtpd-amavis/smtpd[60011]: 00DA8260908: client=localhost[127.0.0.1]
Jan  4 15:12:31 mx postfix/cleanup[60012]: 00DA8260908: message-id=<e97e476d070706773bd36869a5de0847@domain>
Jan  4 15:12:31 mx postfix/qmgr[1887]: 00DA8260908: from=<sender@domain>, size=899, nrcpt=1 (queue active)
Jan  4 15:12:31 mx postfix/smtpd-amavis/smtpd[60011]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Jan  4 15:12:31 mx amavis[42866]: (42866-09) Passed CLEAN {RelayedInbound}, [<External IPv6 Address>]:59632 [<External IPv6 Address>] <sender@domain> -> <reciever@domain>, Queue-ID: 4F63E260907, Message-ID: <e97e476d070706773bd36869a5de0847@domain>, mail_id: l9huTHa08wBH, Hits: 1.784, size: 681, queued_as: 00DA8260908, 691 ms
Jan  4 15:12:31 mx postfix/smtp-amavis/smtp[60006]: 4F63E260907: to=<reciever@domain>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.7, delays=0.01/0/0.01/0.69, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 00DA8260908)
Jan  4 15:12:31 mx postfix/qmgr[1887]: 4F63E260907: removed
Jan  4 15:12:31 mx dovecot: lmtp(60308): Connect from local
Jan  4 15:12:31 mx postfix/lmtp[60013]: 00DA8260908: to=<reciever@domain>, relay=mx.domain[/var/run/dovecot/lmtp], delay=0.06, delays=0.01/0/0.01/0.03, dsn=2.0.0, status=sent (250 2.0.0 <reciever@domain> XPfQAU+JtWOU6wAAHMQWUA Saved)
Jan  4 15:12:31 mx dovecot: lmtp(reciever@domain)<60308><XPfQAU+JtWOU6wAAHMQWUA>: sieve: msgid=<e97e476d070706773bd36869a5de0847@domain>: stored mail into mailbox 'INBOX'
Jan  4 15:12:31 mx dovecot: lmtp(60308): Disconnect from local: Client has quit the connection (state=READY)
Jan  4 15:12:31 mx postfix/qmgr[1887]: 00DA8260908: removed
```

**Comment by casperklein** [comment]
> As ossec does not support authorization for mails I configured postfix with permit_mynetworks

You might take a look at [PERMIT_DOCKER](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#permit_docker).

> But I still see the warning messages in my log.

Is the warning in the logs your only issue? I think, as long as your IPv6 address is not in the container `/etc/hosts` file, this warning is normal and can be ignored.

**Comment by N1k145** [comment]
Thanks, I will have a look.
Yes, my hosts file only contains the docker IPs

The warning is my only issue, but I believe only because I have not set `reject_unknown_client_hostname`
Would this be enabled these mails would be rejected, so the same issue as @mpldr has.

I also had an issue with the new opendmarc RejectFailures true rule, as my ossec mails were also rejected, that was the reason I started to investigate and found this issue here.

**Comment by casperklein** [comment]
>  but I believe only because I have not set reject_unknown_client_hostname

Can you verify that?

**Comment by N1k145** [comment]
I just checked it, of course it depends on the order. If I put 
`smtpd_sender_restrictions = reject_unknown_client_hostname, permit_mynetworks, permit_sasl_authenticated, reject_unknown_sender_domain, reject_sender_login_mismatch`
it's rejected:
```
Jan  4 16:41:57 mx postfix/smtpd[2004]: warning: hostname mx.domain does not resolve to address <External IPv6 Address>
Jan  4 16:41:57 mx postfix/smtpd[2004]: connect from unknown[<External IPv6 Address>]
Jan  4 16:41:57 mx postfix/smtpd[2004]: NOQUEUE: reject: RCPT from unknown[<External IPv6 Address>]: 450 4.7.25 Client host rejected: cannot find your hostname, [<External IPv6 Address>]; from=<sender@domain> to=<reciever@domain> proto=SMTP helo=<notify.ossec.net>
Jan  4 16:41:57 mx postfix/smtpd[2004]: lost connection after RCPT from unknown[<External IPv6 Address>]
```
When I put it the other way around:
smtpd_sender_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unknown_client_hostname, reject_unknown_sender_domain, reject_sender_login_mismatch

My "local" mails are accepted, as they are part of mynetworks, but external mails that run into the same issue should be rejected. 
I currently don't know about any external senders that are not working for me, as I had this disabled all the time

**Comment by GoliathLabs** [comment]
It works fine for me. It looks like a DNS problem to me tbh as the reverse DNS lookup works on my end.

**Comment by GoliathLabs** [comment]
@N1k145 does it change anything if you provide a dns section. E.g.:
```
    dns:
      - 5.1.66.255
      - 185.150.99.255
      - "2001:678:e68:f000::"
      - "2001:678:ed0:f000::"
```

**Comment by GoliathLabs** [comment]
Personally, I'm using ipv6nat, but it seems that you provide a proper public IPv6 to your mail server container, right?

**Comment by N1k145** [comment]
@GoliathLabs more or less yes, I enabled the IPv6 Support in docker:
[https://docs.docker.com/config/daemon/ipv6/](https://docs.docker.com/config/daemon/ipv6/)

My configuration looks like this:
```
cat /etc/docker/daemon.json 
{
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80",
  "experimental": true,
  "ip6tables": true 
}
```

The IPv6 address defined in the compose file is not my external one, but the one used for the docker container, like with the 172.19 address for IPv4:

Part of the docker inspect:
```
        "Networks": {
            "mailserver_mailserver": {
                "IPAMConfig": null,
                "Links": null,
                "Aliases": [
                    "05ad8de9f828",
                    "mailserver",
                    "mx"
                ],
                "Gateway": "172.19.0.1",
                "IPAddress": "172.19.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "2001:3984:3989::1",
                "GlobalIPv6Address": "2001:3984:3989::2",
                "GlobalIPv6PrefixLen": 64,
                "DriverOpts": null
            }
        }
```

So from my understanding, this is now the same behavior as docker uses for IPv4.

I added the DNS section to my compose file, but I get the same message without any differences.
I tried around with dig again, in both direction, so my reverse lookup provides the correct domain name and my domain has the correct AAAA record to the IP Address shown in the log. 
Maybe this is related to the hosts file and postfix falling back to native hostname lookup, or something like this. I have no idea currently

**Comment by AlperShal** [comment]
@N1k145 were you able to fix your problem? I am in a very similar situation if the sender server uses iPv6 (like gmail.com). 



docker attach mailserver --sig-proxy=false
```
Jan 22 22:54:02 mail postfix/postscreen[1394]: CONNECT from [172.27.0.1]:51290 to [172.27.0.2]:25
Jan 22 22:54:08 mail postfix/postscreen[1394]: PASS NEW [172.27.0.1]:51290
Jan 22 22:54:08 mail postfix/smtpd[1416]: connect from unknown[172.27.0.1]
Jan 22 22:54:08 mail postfix/smtpd[1416]: Anonymous TLS connection established from unknown[172.27.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
Jan 22 22:54:08 mail postfix/smtpd[1416]: NOQUEUE: reject: RCPT from unknown[172.27.0.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [172.27.0.1]; from=<alpersal235@gmail.com> to=<alper@sal.web.tr> proto=ESMTP helo=<mail-pl1-x629.google.com>
```

If I remove my DNS AAAA record `CONNECT from [172.27.0.1]:51290 to [172.27.0.2]:25` changes to `CONNECT from [Google's IPv4 address]:51290 to [172.27.0.2]:25` and everything works fine. No `RCPT from unknown[172.27.0.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [172.27.0.1];` error.

Also, if I add this to my `docker-compose.yml`, just `CONNECT from [172.27.0.1]:51290 to [172.27.0.2]:25` changes to `CONNECT from [Docker iPv6 Gateaway Address]:51290 to [Docker Container iPv6 Address]:25` .

```
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:0123:4567::/48
          gateway: fd00:0123:4567::1
````

(Since this issue isn't marked as closed yet, I am asking here. Appreciate any help.)

**Comment by N1k145** [comment]
@AlperShal no, but I have a different issue than you have.
I had your issue a year ago or so while initially setting up the mail server. 
From what I understand you are not seeing external ipv6 addresses in your container.
You can try to set up the demon.json like i showed im my post above. I think this was my solution to get the public ipv6 addresses.

**Comment by N1k145** [comment]
@AlperShal have you restarted the docker daemon process? Not only the container? 
Maybe I also had to set up something in IP tables. I think I googled around for getting ipv6 in docker and found some solutions there

**Comment by GoliathLabs** [comment]
@casperklein at this point it might be a good idea to make this option configurable via environment variables. What do you think about this?

A default "on" policy, but which can be disabled if an ipv6 implementation does not work as expected?

**Comment by N1k145** [comment]
@AlperShal I looked around a bit and found that I have set 
```
sysctl net.ipv6.conf.default.forwarding=1
sysctl net.ipv6.conf.all.forwarding=1
```
and in the env file:
```
POSTFIX_INET_PROTOCOLS=all
DOVECOT_INET_PROTOCOLS=all
```

But I have no Iptables Rules or any other config I could find. Actually, I have no idea why it is working.

@casperklein 
When you disable the IPv6 for the container but leave it visible in your DNS config, the Setup will NAT everything and every IPv6 access will come from the same IPv4 address. And that one will be blocked by fail2ban really quick. That was my initial problem after that I investigated the v6 setup.

**Comment by casperklein** [comment]
> @casperklein at this point it might be a good idea to make this option configurable via environment variables

This, or a bit of documentation on how to disable it via `user-patches.sh`.
