### ISSUE TITLE
Dovecot needs at least on mail account to start

### ISSUE THREAD

**Issue by Tritomit-AP** [docker-mailserver/docker-mailserver#3034]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

You need at least one mail account to start Dovecot

### What happened and when does this occur?

```Markdown
The mailserver does not start, because Dovecot needs at least one mail account. This occurs when using docker-compose up to start the mail server container and even after an mail account was already added.
```

### What did you expect to happen?

```Markdown
I expected to run the container (mailserver), create the rest of config, dkim etc and use this in production to send confirmation emails, reset passwords etc.
```

### How do we replicate the issue?

```Markdown
1. Create directory for mailserver
2. Create docker-compose.yml file inside directory
3. Create email account with `./setup.sh email add email@domain.com password` from root dir.
4. Add rules for ports 25, 465, 587
5. Add SPF record for mail-server.domain.com
6. Back in mailserver dir. run docker-compose up
```

### DMS version

v11.3.0

### What operating system is DMS running on?

Linux

### Which operating system version?

Ubuntu 20.04

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
version: '3.8'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail-server
    domainname: domain.com
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/nginx-proxy/certs/:/usr/local/psa/var/modules/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      - SPOOF_PROTECTION=0
      - LOG_LEVEL=debug
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
      - SYS_PTRACE
```

### Relevant log output

```bash
mailserver    | [  DEBUG  ]  Handling general environment variable setup
mailserver    | [   INF   ]  Welcome to docker-mailserver 11.3.0
mailserver    | [   INF   ]  Initializing setup
mailserver    | [  DEBUG  ]  Registering functions
mailserver    | [   INF   ]  Checking configuration
mailserver    | [  DEBUG  ]  Checking that hostname/domainname is provided or overridden
mailserver    | [  DEBUG  ]  Domain has been set to domain.com
mailserver    | [  DEBUG  ]  Hostname has been set to mail-server.domain.com
mailserver    | [   INF   ]  Configuring mail server
mailserver    | [  DEBUG  ]  Setting file and directory permissions
mailserver    | [  DEBUG  ]  Setting up Dovecot
mailserver    | [  DEBUG  ]  Spam messages will be moved to the Junk folder
mailserver    | [  DEBUG  ]  Setting up Dovecot dhparam
mailserver    | [  DEBUG  ]  Setting up Dovecot quota
mailserver    | [  DEBUG  ]  Setting up Dovecot Local User
mailserver    | [ WARNING ]  You need at least one mail account to start Dovecot (120s left for account creation before shutdown)
mailserver    | [ WARNING ]  You need at least one mail account to start Dovecot (110s left for account creation before shutdown)
mailserver    | [ WARNING ]  You need at least one mail account to start Dovecot (100s left for account creation before shutdown)
```

### Other relevant information

```Markdown
There is already a mail account created so I'm not sure what Dovecot is exactly looking for. The added mail account can be verified via `./setup.sh email list` .
```

### What level of experience do you have with Docker and mail servers?

- [X] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
Please start the mail server, and then, when the message `You need at least one mail account to start Dovecot` is printed, run the `./setup.sh email add email@domain.com password`. `setup.sh` does not know about any running container in your setup (because when you executed it, no DMS container was running), or you have not provided `-p <CONFIG VOLUME DIR>`, which would work as well.

**Comment by Tritomit-AP** [comment]
Yes, this solved my issue, thank you a lot!

**Comment by danielkrajnik** [comment]
This has been [changed](https://docker-mailserver.github.io/docker-mailserver/edge/usage/#get-up-and-running) to `docker exec -ti <CONTAINER NAME> setup email add user@example.com`
