### ISSUE TITLE
[BUG] logrotate state file /var/lib/logrotate/state should be moved to "mail-state" persistent storage

### ISSUE THREAD

**Issue by IvanI3** [docker-mailserver/docker-mailserver#3075]
### Miscellaneous first checks

- [x] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

logrotate

### What happened and when does this occur?

```Markdown
Currently "/var/lib/logrotate/state" placed to non-persistent directory, so after DMS container restarts, logrotates creates new "states" with boot time rotation timestamps for all logfiles.
So, if your, for example, restart DMS during a week, "weelky" logrotates will not occur at sunday.
```

### What did you expect to happen?

```Markdown
I think log files shoud be rotated _every_ week at sunday, as it's configured. It should not depends on server reboots.
To do so, logrotate state directory must be placed at "/var/mail-state/lib-logrotate" and symlinked to "/var/lib/logrotate" same way as other persistent dirs.
```

### How do we replicate the issue?

```Markdown
1. run in container: logrotate -d /etc/logrotate.conf
mention last log rotation dates
2. restart DMS contaiter
3. run in container again: logrotate -d /etc/logrotate.conf
/var/lib/logrotate/state file would be newly created, last rotation in it - the DMS boot time
4. weekly logrotate won't occur at next sunday
```

### DMS version

v.11.3.1

### What operating system is DMS running on?

Linux

### Which operating system version?

Ubuntu 22.04

### What instruction set architecture is DMS running on?

ARM64 / AArch64 (ARM v8 and newer)

### What container orchestration tool are you using?

Kubernetes (not officially supported)

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
@casperklein @polarathene thoughts? I don't see a problem. The solution is _probably_ less than 10 SLoC.
