### ISSUE TITLE
[BUG] Dovecot: login does not work because of ftx_xapian library error

### ISSUE THREAD

**Issue by prosith** [docker-mailserver/docker-mailserver#3100]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Dovecot

### What happened and when does this occur?

After enabling full text search with xapian according this guide:
https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/full-text-search/

The client cannot login via IMAP. The logs show a version issue.

### What did you expect to happen?

Fulltextsearch is working

### How do we replicate the issue?

1. Update to latest edge version
2. Enable xapian fulltext search plugin
3. restart docker-mailserver
4. connect via IMAP
...

### DMS version

v11.3.1

### What operating system is DMS running on?

Linux

### Which operating system version?

Ubuntu 22.04

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker-compose

### docker-compose.yml

```yml
services:
  mailserver:
    #image: docker.io/mailserver/docker-mailserver:latest
    image: docker.io/mailserver/docker-mailserver:edge
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: ####
    domainname: ####.##
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/config/dovecot/fts-xapian-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```Text
Error: Couldn't load required plugin /usr/lib/dovecot/modules/lib21_fts_xapian_plugin.so: Module is for different ABI version 2.3.ABIv13(2.3.13) (we have 2.3.ABIv20(2.3.20))
```

### Other relevant information

Thanks for your support! :)

### What level of experience do you have with Docker and mail servers?

- [X] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
I remeber we had issues with xapian, hence the path release [`v11.3.1`](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v11.3.1), but as it seems, we did not resolve the issue properly other than with a solution you won't like: rebuild DMS and use `export DOVECOT_COMMUNITY_REPO=0` before running `make build`. If you run DMS via Docker Compose (not inside a Kubernes cluster where you'd need to push the image to a registry), this _should in theory_ work:

```console
$ export DOVECOT_COMMUNITY_REPO=0
$ make IMAGE_NAME=docker-mailserver:local build
```

You should then be able to use `docker-mailserver:local` in your Compose file and run DMS with an older version of Dovecot which should support Xapian IIRC.
