### ISSUE TITLE
[BUG] `/var/mail-state/spool-postfix/` not created with VirtioFS on macOS

### ISSUE THREAD

**Issue by carlosfrodriguez** [docker-mailserver/docker-mailserver#3164]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Services can not start if switch to VirtioFS

### What happened and when does this occur?

I have docker-mailserver running correctly with in my Mac with docket desktop 4.17.0, Engine: 20.10.23, Compose: v2.15.1 using file sharing gRPC FUSE, but as long as I switch to VirtioFS, the container reports missing files and issues setting permissions and the services can not start anymore.

I already try to delete the container, and the image and start from the scratch but there is no difference, I restart the docker desktop but still the same issue.

All other containers works well but they use local volumes instead of binding folders as suggested in docker-mailserver documentation.

### What did you expect to happen?

That the services starts correctly

### How do we replicate the issue?

1. Copy the download mailserver.env (as in the documentation) and put it with the docker-compose.yml file
2. Set the VirtioFS as sharing implementation
3. Pull the image
4. Start the container with docker-compose

### DMS version

v11.3.1

### What operating system is DMS running on?

macOS (not officially supported)

### Which operating system version?

MacOS 13.2.1

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: sith.net
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```Text
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/smtp': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/virtual': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/proxymap': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/scache': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/proxywrite': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/relay': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/anvil': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/error': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/bounce': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/private/smtp-amavis': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/dev/log': Invalid argument
2023-03-07 08:56:40 chgrp: changing group of '/var/mail-state/spool-postfix/public/qmgr': No such file or directory
2023-03-07 08:56:40 chgrp: changing group of '/var/mail-state/spool-postfix/public/flush': No such file or directory
2023-03-07 08:56:40 chgrp: changing group of '/var/mail-state/spool-postfix/public/sender-cleanup': No such file or directory
2023-03-07 08:56:40 chgrp: changing group of '/var/mail-state/spool-postfix/public/showq': No such file or directory
2023-03-07 08:56:40 chgrp: changing group of '/var/mail-state/spool-postfix/public/cleanup': No such file or directory
2023-03-07 08:56:40 chown: changing ownership of '/var/mail-state/spool-postfix/dev/log': Invalid argument
2023-03-07 08:56:40 [   INF   ]  Starting daemons
2023-03-07 08:56:42 [   INF   ]  mail.sith.net is up and running
2023-03-07 08:56:43 Mar  7 08:56:42 mail dovecot: master: Error: service(auth): chown(/var/spool/postfix/private/auth, 5000, 5000) failed: Invalid argument
2023-03-07 08:56:43 Mar  7 08:56:42 mail dovecot: master: Fatal: Failed to start listeners
2023-03-07 08:56:43 Mar  7 08:56:42 mail dovecot: master: Error: service(auth): chown(/var/spool/postfix/private/auth, 5000, 5000) failed: Invalid argument
2023-03-07 08:56:43 Mar  7 08:56:42 mail dovecot: master: Fatal: Failed to start listeners
2023-03-07 08:56:43 Mar  7 08:56:42 mail dovecot: master: Error: service(auth): chown(/var/spool/postfix/private/auth, 5000, 5000) failed: Invalid argument
2023-03-07 08:56:43 Mar  7 08:56:42 mail dovecot: master: Fatal: Failed to start listeners
2023-03-07 08:56:43 Mar  7 08:56:42 mail dovecot: master: Error: service(auth): chown(/var/spool/postfix/private/auth, 5000, 5000) failed: Invalid argument
```

### What level of experience do you have with Docker and mail servers?

- [X] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
Are you running `:edge` or `v11.3.1`?

**Comment by georglauterbach** [comment]
You are using macOS, and you have probably already read this is not officially supported. I don't know why `/var/mail-state/spool-postfix/` is not present, but if I had to guess: the underlying FS (i.e. VirtioFS) does not support symlinking, which we do when `ONE_DIR=1`.

I am very sorry, but this is nothing we can resolve at the moment, because we rely on symbolic links to properly work :(

**Comment by reneploetz** [comment]
Linking the underlying issue from Docker-For-Mac that you also commented on @carlosfrodriguez

https://github.com/docker/for-mac/issues/6243

In  short: Docker for Mac using VirtioFS has a bug that upstream is working on. Not ETA given there. You have to use gRPC Fuse for now.

**Comment by carlosfrodriguez** [comment]
Thanks @reneploetz @georglauterbach

**Comment by georglauterbach** [comment]
Thank you @reneploetz! I will then go ahead and close this because this is not a DMS issue :)

**Comment by polarathene** [comment]
> but if I had to guess: the underlying FS (i.e. VirtioFS) does not support symlinking, which we do when `ONE_DIR=1`.

Isn't the symlink created at the other end, outside of the `/var/mail-state` volume? (_which then holds the copied data to link to_)

Filesystem support for certain features of `/var/mail-state` (_and probably other mounts we support_) is also probably important. Not that anyone is likely to bind mount to FAT32 or anything similar :sweat_smile:
