### ISSUE TITLE
[BUG] UNCHECKED contents in mail FROM with PGP encrypted email

### ISSUE THREAD

**Issue by winny-** [docker-mailserver/docker-mailserver#3166]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

I think this email is sent by the antivirus scanner.

### What happened and when does this occur?

Send a pgp encrypted email.

### What did you expect to happen?

Find a way to suppress these `UNCHECKED contents in mail FROM` emails because encrypted emails should be unchecked.

### How do we replicate the issue?

1. Guessing: Set up AVIS
2. Send a PGP email
3.
...

### DMS version

latest

### What operating system is DMS running on?

Linux

### Which operating system version?

Ubuntu 20.04.5 LTS

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### Other relevant information

I saw this ticket, looked similar, wasn't able to find the linked wiki content.  https://github.com/docker-mailserver/docker-mailserver/issues/682#issuecomment-323508591

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
[This](https://serverfault.com/a/539377) could solve your problem.

[Here](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/optional-config/) you find information on how to customize amavis in DMS.

**Comment by williamdes** [comment]
Stupid bot

**Comment by williamdes** [comment]
it is probably worth adding a documentation block or a rule for this.I also run into this message quite often

**Comment by demaniak** [comment]
> [This](https://serverfault.com/a/539377) could solve your problem.
> 
> [Here](https://docker-mailserver.github.io/docker-mailserver/v13.3/config/advanced/optional-config/) you find information on how to customize amavis in DMS.

So just to spell it out:
- create a `amavis.cf` file in the volume where you carry the other config files
- add this line to the `amavis.cf` file:  `$admin_maps_by_ccat{+CC_UNCHECKED.',1'} = undef;`
- restart docker-mailserver
- optional : commit the change to your git repo holding your config files :)

**Comment by winny-** [comment]
Hi, thank you for the clarified steps!

I no longer operate a docker-mailserver instance and it follows that I'll recuse myself from this discussion.
