### ISSUE TITLE
[BUG] setup email add creating inbox for domain but had to create local user for another inbox

### ISSUE THREAD

**Issue by mecherin** [docker-mailserver/docker-mailserver#3212]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postfix

### What happened and when does this occur?

The account was created, I could receive inbox, but one day it stopped receiving emails with the following message:

Recipient address rejected: User unknown in local recipient table;

### What did you expect to happen?

To receive the email on my smartphone

### How do we replicate the issue?

1. Pull edge version from GitHub
2. Configure docker-compose.yml and mailserver.env
3. Setup lets encrypt and everything you need
4. Add a valid recipient
5. Create some aliases
6. Add the user in the docker container with user add (this is no sense)

### DMS version

edge

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian 11.6

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
services:
  mailserver:
    image: docker-mailserver:edge
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: xxx.tld
#    domainname:
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt/live/xxx.tld/:/etc/letsencrypt/live/xxx.tld/:ro
      - /etc/letsencrypt/archive/xxx.tld-0001/:/etc/letsencrypt/archive/xxx.tld/:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```Text
Recipient address rejected: User unknown in local recipient table;
```

### Other relevant information

I could receive but one day it stopped and I don't know exactly why, if it was because adding aliases or what.

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

Why do you need the Debian version if the image version uses the Dockerfile version?

**Comment by georglauterbach** [comment]
> Why do you need the Debian version if the image version uses the Dockerfile version?

Because we need information on, e.g. the hosts kernel version in order to evaluate issues with netfilter and containerization support.

---

It is highly unlikely (I use this term, when in fact I should say: almost impossible) that DMS removed an account on its own. It is way more likely

1. the host had some changes to its file system where files are bind-mounted into the container, and this in turn affected the container - please check the volumes!
2. you actually did something; you said it just happened without any obvious cause, but then you also say

> if it was because adding aliases or what.

So did you add an alias? Did you do anything else on the host?

---

> 6. Add the user in the docker container with user add (this is no sense)

Yes, this is nonsensical. Why did you do that? This serves absolutely no purpose whatsoever and is not required at all.

**Comment by mecherin** [comment]
> > Why do you need the Debian version if the image version uses the Dockerfile version?
> 
> Because we need information on, e.g. the hosts kernel version in order to evaluate issues with netfilter and containerization support.

Okay.
> 
> It is highly unlikely (I use this term, when in fact I should say: almost impossible) that DMS removed an account on its own. It is way more likely
>
the account is not removed, I run $ setup email list # and it appears, also with alias. I also checked postfix-accounts.cf and it is there. 
> 1. the host had some changes to its file system where files are bind-mounted into the container, and this in turn affected the container - please check the volumes!
I can see the volumes are right, I mean, the structure file seems to be like in the beginning.
> 2. you actually did something; you said it just happened without any obvious cause, but then you also say
> 
> > if it was because adding aliases or what.
> 
> So did you add an alias? Did you do anything else on the host?
> 
I don't remember exactly what I did more than adding some SPF entries on NS. I just sent some emails to abuse@ when receiving a lot of tries into my web server, the mails were going out and coming out, but only could prove it few. When I started to use it seriously is not receiving without the system (container) account.
> > 6. Add the user in the docker container with user add (this is no sense)
> 
> Yes, this is nonsensical. Why did you do that? This serves absolutely no purpose whatsoever and is not required at all.
I did because I imagined that the DMS is working fine but by an unknown reason is using the system users, which may not because it should work with setup script.


What can I do? Do I remove the system account and try again? This has no sense. I think some configuration of postfix or dunno is not loading the cfg of working with the default setup of users.

As I said, the following commands are returning the inboxes setup:

# setup email list
* xxx@xxx.tld ( 62K / ~ ) [0%]
    [ aliases -> postmaster@xxx.tld, webmaster@xxx.tld, contact@xxx.tld, xxxx@xxx.tld ]

I can remove everything and reinstall but what if it happens again?

Being sincere I don't know what did I do to break it. I left it working and the only modifications I did was with NS to add SPF, reverse and I remember first I was using mail.xxx.tld and changed to xxx.tld. Maybe was this... what should I do?

**Comment by georglauterbach** [comment]
> I was using mail.xxx.tld and changed to xxx.tld

Try reverting that, yes.

---

You also seem to have an alias `xxx@xxx.tld` that points to the same account. Definitely remove this alias.

**Comment by mecherin** [comment]
> > I was using mail.xxx.tld and changed to xxx.tld
> 
> Try reverting that, yes.

But I want the actual domain, can't it be changed?
> 
> You also seem to have an alias `xxx@xxx.tld` that points to the same account. Definitely remove this alias.
No, the alias is xxxx not xxx. No aliases are the same as account.

**Comment by georglauterbach** [comment]
> > > I was using mail.xxx.tld and changed to xxx.tld
> > 
> > 
> > Try reverting that, yes.
> 
> But I want the actual domain, can't it be changed?

This is a (typical) misconception. You will likely want to run you mail server as `mail.xxx.tld`, then have an A record `mail.xxx.tld -> 1.2.3.4` (some IP) and an MX record for `xxx.tld` that contains `mail.xxx.tld`.

We currently lack documentation for this, but [Mailq has a nice documentation for this](https://docs.mailcow.email/prerequisite/prerequisite-dns/).

> > You also seem to have an alias `xxx@xxx.tld` that points to the same account. Definitely remove this alias.
> 
> No, the alias is xxxx not xxx. No aliases are the same as account.

Sorry, my bad.

**Comment by mecherin** [comment]
> > > > I was using mail.xxx.tld and changed to xxx.tld
> > > 
> > > 
> > > Try reverting that, yes.
> > 
> > 
> > But I want the actual domain, can't it be changed?
> 
> This is a (typical) misconception. You will likely want to run you mail server as `mail.xxx.tld`, then have an A record `mail.xxx.tld -> 1.2.3.4` (some IP) and an MX record for `xxx.tld` that contains `mail.xxx.tld`.
> 
> We currently lack documentation for this, but [Mailq has a nice documentation for this](https://docs.mailcow.email/prerequisite/prerequisite-dns/).
> 

Thank you, it is working now.
> > > You also seem to have an alias `xxx@xxx.tld` that points to the same account. Definitely remove this alias.
> > 
> > 
> > No, the alias is xxxx not xxx. No aliases are the same as account.
> 
> Sorry, my bad.

Don't worry.

**Comment by georglauterbach** [comment]
So this issue can be closed?

**Comment by mecherin** [comment]
> So this issue can be closed?

Yes.
