### ISSUE TITLE
[BUG] Failed to initialize user: Couldn't drop privileges: User is missing UID (see mail_uid setting)

### ISSUE THREAD

**Issue by mhclaudiu** [docker-mailserver/docker-mailserver#3218]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

LDAP authentication

### What happened and when does this occur?

When receiving emails to ldap users

### What did you expect to happen?

LDAP succesfull auth

### How do we replicate the issue?

Deploy the container, and wait for logs output

### DMS version

11.3.0

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian 11

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
version: '3.8'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.domain.com
    domainname: domain.com

    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"

    volumes:
      - ./data/dms/mail-data/:/var/mail/
      - ./data/dms/mail-state/:/var/mail-state/
      - ./data/dms/mail-logs/:/var/log/mail/
      - ./data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro

    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0

      # >>> Postfix LDAP Integration
      - ENABLE_LDAP=1 # with the :edge tag, use ACCOUNT_PROVISIONER
      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_SERVER_HOST=dc1.domain.com
      - LDAP_BIND_DN=user
      - LDAP_BIND_PW=pass
      - LDAP_SEARCH_BASE=cn=Users,dc=domain,dc=com
      - LDAP_QUERY_FILTER_DOMAIN=(|(mail=*@%s)(mailAlias=*@%s)(mailGroupMember=*@%s))
      - LDAP_QUERY_FILTER_USER=(&(objectClass=user)(mail=%s))
      - LDAP_QUERY_FILTER_ALIAS=(&(objectClass=user)(mailAlias=%s))
      - LDAP_QUERY_FILTER_GROUP=(&(objectClass=group)(mailGroupMember=%s))
      - LDAP_QUERY_FILTER_SENDERS=(&(objectClass=user)(|(mail=%s)(mailAlias=%s)(mailGroupMember=%s)))
      - SPOOF_PROTECTION=1
      # <<< Postfix LDAP Integration

      # >>> Dovecot LDAP Integration
      - DOVECOT_USER_FILTER=(&(objectClass=user)(mail=%u))
      - DOVECOT_PASS_ATTRS=uid=user,userPassword=password
      - DOVECOT_USER_ATTRS==home=/var/mail/%{ldap:uid},=mail=maildir:~/Maildir,uidNumber=uid,gidNumber=gid
      # <<< Dovecot LDAP Integration

      # >>> SASL LDAP Authentication
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_FILTER=(&(mail=%U@domain.com)(objectClass=user))
      # <<< SASL LDAP Authentication

      - ONE_DIR=1
      - SSL_TYPE=
      - PERMIT_DOCKER=host

    cap_add:
      - NET_ADMIN
```

### Relevant log output

```Text
Apr  3 17:00:29 mail dovecot: lmtp(2551, claudium@domain.com): Error: lmtp-server: conn unix:pid=2550,uid=101 [1]: rcpt claudium@domain.com: Failed to initialize user: Couldn't drop privileges: User is missing UID (see mail_uid setting)
```

### What level of experience do you have with Docker and mail servers?

- [X] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by polarathene** [comment]
No maintainer has LDAP experience to provide assistance. We can only refer you to community contributed examples in our docs, our test suite and to search our issues / discussions from other LDAP users.

You've made no indication of DMS + LDAP working for you previously, and we have users that do run with LDAP successfully, so this is likely not a bug on our end but misconfiguration.

**Comment by mhclaudiu** [comment]
Thank you, well about the misconfiguration, is there something wrong regarding to the container config that i posted here? It's the example taken from the docs.
Active directory is a windows server 2019, i'm having just an simple user in Users CN - claudium, no special configuration.

**Comment by polarathene** [comment]
> Active directory is a windows server 2019

That may be the issue? :man_shrugging: 

I have heard of openldap being used, not sure what else. Search the issues we have for LDAP ones. I recall that some LDAP services don't work so well.

Your issue will be LDAP related, I'm not able to assist there. Docs is community contributed like I said, we don't know anything about LDAP.

**Comment by polarathene** [comment]
```
    hostname: mail.domain.com
    domainname: domain.com
```

That is wrong though, and should just be the `hostname` line. Don't use the `domainname` line.
