### ISSUE TITLE
[BUG] LOGIN authentication failed: Connection lost to authentication server

### ISSUE THREAD

**Issue by mistek131995** [docker-mailserver/docker-mailserver#3227]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I read the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue.

### Affected Component(s)

I can't send email when have this error

### What happened and when does this occur?

Apr  7 05:20:45 mail postfix/submission/smtpd[31519]: warning: connect to Milter service inet:localhost:8891: Network is unreachable
Apr  7 05:20:45 mail postfix/submission/smtpd[27640]: warning: unknown[46.148.40.64]: SASL LOGIN authentication failed: Connection lost to authentication server
Apr  7 05:20:46 mail postfix/submission/smtpd[27640]: disconnect from unknown[46.148.40.64] ehlo=1 auth=0/1 rset=1 quit=1 commands=3/4
Apr  7 05:20:48 mail dovecot: auth: Warning: auth client 0 disconnected with 1 pending requests: Connection reset by peer
Apr  7 05:20:51 mail dovecot: auth: passwd-file(brian@relocant.info,46.148.40.64): unknown user (SHA1 of given password: 8cb223)
Apr  7 05:20:51 mail postfix/submission/smtpd[32505]: connect from unknown[46.148.40.64]

### What did you expect to happen?

It is do't work after small time...

### How do we replicate the issue?

1. Enadle container
2. Send email
3. Wait
4. Repeat if container is work

### DMS version

11.3.0

### What operating system is DMS running on?

Linux

### Which operating system version?

CensOS 7

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.relocant.info
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m
    ports:
      - "25:25"
      - "587:587"
      - "143:143"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=1
    cap_add:
      - NET_ADMIN
    restart: always
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by polarathene** [comment]
`memory: 512m`

This is too low with features like `ENABLE_CLAMAV=1`.

**Comment by georglauterbach** [comment]
Clasing because no feedback from OP.
