### ISSUE TITLE
bug report: fail2ban doesn't seem to work

### ISSUE THREAD

**Issue by joopdo** [docker-mailserver/docker-mailserver#3238]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue.
- [X] I read the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue.

### Affected Component(s)

fail2ban

### What happened and when does this occur?

First off: Thank you for docker-mailserver. I'm user for a few years and it really works well! I was thinking: wouldn't it be great if docker-mailserver had fail2ban? Turns out, you do! Awesome! Thank you. Yesterday I switched it on but it doesn't seem to work for me.

I am trying to configure fail2ban on a Docker container, but I am unable to get it working. Specifically, the bans are not being applied to the IP addresses that are repeatedly attempting to access my server.

### What did you expect to happen?

The IP addresses are detected by fail2ban, but the bans are not being applied.

### How do we replicate the issue?

1. Create a docker-mailserver Docker container 
2. Configure the fail2ban settings per the documentation. (https://docker-mailserver.github.io/docker-mailserver/edge/config/security/fail2ban/ - standard settings)
3. Verify that the fail2ban service is running on the container.
4. Generate some fake traffic to the server to trigger fail2ban bans. (or in my case, I get bombarded anyway)
5. Check the fail2ban logs and confirm that the IP addresses are being detected and banned.
6. Observe that the IP's are able to keep in trying to login and such.

### DMS version

v11.3.1 

### What operating system is DMS running on?

Linux

### Which operating system version?

Linux joop.in 5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 14:02:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
My docker-compose:

`: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: <removed> # <-- CHANGE THIS
    domainname: <removed> # <-- CHANGE THIS
    container_name: mailserver
    env_file: mailserver.env
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    # More information about the mailserver ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "4190:4190"

    volumes:
      - ./data/maildata:/var/mail
      - ./data/mailstate:/var/mail-state
      - ./data/maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./docker-data/dms/cron/sa-learn:/etc/cron.d/sa-learn  
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 512M
            reservations:
              cpus: 0.25
              memory: 128M
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_MANAGESIEVE=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - MOVE_SPAM_TO_JUNK=1
      - ENABLE_FAIL2BAN=1
      - SPOOF_PROTECTION=1
        #      - LOG_LEVEL=debug
      - SA_SHORTCIRCUIT_BAYES_SPAM=1
    restart: always
    stop_grace_period: 1m
      # cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
    cap_add:
      - NET_ADMIN
`
```

### Relevant log output

```Text
/var/log/fail2ban.log (on the docker container)

`-04-09 20:24:50,886 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:24:52,269 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:27:31,516 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:27:34,021 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:29:18,126 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:29:20,394 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:31:34,751 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:31:35,968 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:34:03,467 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:34:05,252 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:35:41,760 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:35:42,825 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:37:29,063 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:39:06,200 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:39:07,629 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:41:59,540 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:42:01,520 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:43:51,575 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:43:53,588 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:48:21,674 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:48:23,659 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:51:45,557 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:51:47,558 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:53:30,984 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:53:32,987 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned
2023-04-09 20:55:47,328 fail2ban.actions        [833]: WARNING [dovecot] 141.98.10.XXX already banned
2023-04-09 20:55:49,331 fail2ban.actions        [833]: WARNING [postfix-sasl] 141.98.10.XXX already banned

`
```

### Other relevant information

````
cat fail2ban-*
# Fail2Ban main configuration file
#
# Comments: use '#' for comment lines and ';' (following a space) for inline comments
#
# Changes:  in most of the cases you should not modify this
#           file, but provide customizations in fail2ban.local file, e.g.:
#
# [Definition]
# loglevel = DEBUG
#

[Definition]

# Option: loglevel
# Notes.: Set the log level output.
#         CRITICAL
#         ERROR
#         WARNING
#         NOTICE
#         INFO
#         DEBUG
# Values: [ LEVEL ]  Default: ERROR
#
#loglevel = INFO

# Option: logtarget
# Notes.: Set the log target. This could be a file, SYSLOG, STDERR or STDOUT.
#         Only one log target can be specified.
#         If you change logtarget from the default value and you are
#         using logrotate -- also adjust or disable rotation in the
#         corresponding configuration file
#         (e.g. /etc/logrotate.d/fail2ban on Debian systems)
# Values: [ STDOUT | STDERR | SYSLOG | SYSOUT | FILE ]  Default: STDERR
#
#logtarget = /var/log/fail2ban.log

# Option: syslogsocket
# Notes: Set the syslog socket file. Only used when logtarget is SYSLOG
#        auto uses platform.system() to determine predefined paths
# Values: [ auto | FILE ]  Default: auto
#syslogsocket = auto

# Option: socket
# Notes.: Set the socket file. This is used to communicate with the daemon. Do
#         not remove this file when Fail2ban runs. It will not be possible to
#         communicate with the server afterwards.
# Values: [ FILE ]  Default: /var/run/fail2ban/fail2ban.sock
#
#socket = /var/run/fail2ban/fail2ban.sock

# Option: pidfile
# Notes.: Set the PID file. This is used to store the process ID of the
#         fail2ban server.
# Values: [ FILE ]  Default: /var/run/fail2ban/fail2ban.pid
#
#pidfile = /var/run/fail2ban/fail2ban.pid

# Options: dbfile
# Notes.: Set the file for the fail2ban persistent data to be stored.
#         A value of ":memory:" means database is only stored in memory 
#         and data is lost when fail2ban is stopped.
#         A value of "None" disables the database.
# Values: [ None :memory: FILE ] Default: /var/lib/fail2ban/fail2ban.sqlite3
#dbfile = /var/lib/fail2ban/fail2ban.sqlite3

# Options: dbpurgeage
# Notes.: Sets age at which bans should be purged from the database
# Values: [ SECONDS ] Default: 86400 (24hours)
#dbpurgeage = 1d
[DEFAULT]

# "bantime" is the number of seconds that a host is banned.
bantime  = 1440m

# A host is banned if it has generated "maxretry" during the last "findtime"
# seconds.
findtime  = 10m

# "maxretry" is the number of failures before a host get banned.
maxretry = 3

# "ignoreip" can be a list of IP addresses, CIDR masks or DNS hosts. Fail2ban
# will not ban a host which matches an address in this list. Several addresses
# can be defined using space (and/or comma) separator.
#ignoreip = 127.0.0.1/8

# Default ban action
# iptables-multiport:	block IP only on affected port
# iptables-allports:	block IP on all ports
banaction = iptables-allports
````

### What level of experience do you have with Docker and mail servers?

- [X] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

none

**Comment by georglauterbach** [comment]
Does it work without custom settings? Please start by removing that first.

We are using `nftables-allports` for the banaction, this is what I immediately noticed.

**Comment by polarathene** [comment]
v12 release will be out soon and made some changes to Fail2Ban. Might be worthwhile confirming if the issue still occurs with v12.

**Comment by joopdo** [comment]
@georglauterbach Thank you for catching `nftables-allport` for `banaction`. I don't know why mine had `iptables-allports` (perhaps it's from an [early version](https://github.com/docker-mailserver/docker-mailserver/blob/a8a8c859dc914a1414304b360cdcd99a1d2ecdf8/config-examples/fail2ban-jail.cf)) Happy to report that with your suggestion, the issue is solved on v11.

@polarathene Exciting news about v11, I'll upgrade my environment soon. I'll write if the issue reappears in V12.
