### ISSUE TITLE
tracking: Stabilization of Rspamd

### ISSUE THREAD

**Issue by georglauterbach** [docker-mailserver/docker-mailserver#3249]
To stabilize Rspamd and allow for it to become the default, we need to do the following:

- [x] correct/adjust/improve the documentation about imprecise/misleasing statements concerning the current status of Rspamd's implementation in DMS and upcoming changes
- [x] add proper, canonical (with DMS' volume directory hierarchy) mount directory paths so users do not need to manually mount to `/etc/rspamd/override.d/`; also adjust docs about `/etc/rspamd/override.d` (see <https://docker-mailserver.github.io/docker-mailserver/edge/config/security/rspamd/#manually>)); this dir will be linked to `/tmp/docker-mailserver/rspamd/override.d/`
- [x] Finish #3228
- [x] Add more unit & integration tests (for multiple configuration options)
- [ ] improve DKIM signing support (does not have to be complete, but aid the user for now)
- [x] add info to docs about `soft_reject_on_timeout` (DNS)
- [x] add `ENABLE_POLICYD_SPF=0` to <https://docker-mailserver.github.io/docker-mailserver/edge/config/security/rspamd/#a-very-basic-configuration>
- [x] add helper for checking if var is a number and check for Rspamd ENV vars
- [x] add checks whether OpenDKIM/OpenDMARC/policyd-spf/Postgrey are enabled
- [x] move `rspamd-modules.conf` into `docker-data/dms/config/rspamd/` and rename it to `custom-commands.conf`; make sure the code catches the old location
