### ISSUE TITLE
bug report: 

### ISSUE THREAD

**Issue by ap-wtioit** [docker-mailserver/docker-mailserver#3251]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue.
- [X] I read the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue.

### Affected Component(s)

tests

### What happened and when does this occur?

When running tests for an older image when a new one is available test `ldap mail delivery works` fails (output from CI)
```
not ok 14 checking dovecot: ldap mail delivery works in 10290ms
# (from function `assert_output' in file test/test_helper/bats-assert/src/assert_output.bash, line 194,
#  in test file test/tests/serial/mail_with_ldap.bats, line 156)
#   `assert_output 1' failed
#
# -- output differs --
# expected : 1
# actual   : 2
# --
#
```

### What did you expect to happen?

Test passes even when newer version is available.

### How do we replicate the issue?

1. run `make` for an old version when a newer version is available

### DMS version

11.3.1

### What operating system is DMS running on?

Linux

### Which operating system version?

Ubuntu 22.04 LTS (local dev), Ubuntu 18.04.6 LTS (CI)

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
-
```

### Relevant log output

```Text
after some investigation with

  run docker exec mail_with_ldap /bin/sh -c "ls -A /var/mail/${FQDN_LOCALHOST_A}/some.user/new && grep -R '.*' /var/mail/${FQDN_LOCALHOST_A}/some.user/new/"
  assert_success
  assert_output 1

i found that the update notification for postmaster affects this test (output from local dev)
```
 ✗ checking dovecot: ldap mail delivery works [10313]
   (from function `assert_output' in file test/test_helper/bats-assert/src/assert_output.bash, line 194,
    in test file test/tests/serial/mail_with_ldap.bats, line 162)
     `assert_output 1' failed
   
   -- output differs --
   expected (1 lines):
     1
   actual (43 lines):
     1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026
     1681201663.M563732P1022.mail.my-domain.com,S=590,W=605
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:Return-Path: <user@external.tld>
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:Delivered-To: some.user@localhost.localdomain
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:Received: from mail.my-domain.com
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:	by mail.my-domain.com with LMTP
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:	id jVJUIf8ZNWT+AwAAUIhAew
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:	(envelope-from <user@external.tld>)
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:	for <some.user@localhost.localdomain>; Tue, 11 Apr 2023 08:27:43 +0000
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:Received: by mail.my-domain.com (Postfix, from userid 0)
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:	id 857262BE93FE; Tue, 11 Apr 2023 08:27:43 +0000 (UTC)
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:Subject: Test Message test-email.txt
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:Message-Id: <20230411082743.857262BE93FE@mail.my-domain.com>
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:Date: Tue, 11 Apr 2023 08:27:43 +0000 (UTC)
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:From: root <user@external.tld>
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563732P1022.mail.my-domain.com,S=590,W=605:This is a test mail.
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Return-Path: <root@mail.my-domain.com>
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Delivered-To: some.user@localhost.localdomain
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Received: from mail.my-domain.com
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:	by mail.my-domain.com with LMTP
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:	id XpAiIf8ZNWT9AwAAUIhAew
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:	(envelope-from <root@mail.my-domain.com>)
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:	for <some.user@localhost.localdomain>; Tue, 11 Apr 2023 08:27:43 +0000
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Received: by mail.my-domain.com (Postfix, from userid 0)
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:	id 8200E2BE943E; Tue, 11 Apr 2023 08:27:42 +0000 (UTC)
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:To: postmaster@localhost.localdomain
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Subject: Mailserver update available! [ 11.3.1 --> 12.0.0 ]
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:MIME-Version: 1.0
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Content-Type: text/plain; charset="UTF-8"
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Content-Transfer-Encoding: 8bit
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Message-Id: <20230411082743.8200E2BE943E@mail.my-domain.com>
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Date: Tue, 11 Apr 2023 08:27:42 +0000 (UTC)
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:From: root <root@mail.my-domain.com>
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Hello postmaster@localhost.localdomain!
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:There is a docker-mailserver update available on your host: mail.my-domain.com
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Current version: 11.3.1
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Latest  version: 12.0.0
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:
     /var/mail/localhost.localdomain/some.user/new/1681201663.M563641P1021.mail.my-domain.com,S=1000,W=1026:Changelog: https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md

```
```

### Other relevant information

I'll prepare a pull request for this

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

Reporting this test error should not require me to check the mailserver ports are open (of course they were not open to the internet during tests) nor the other preliminary checks except the searching for duplicate issues.

**Comment by georglauterbach** [comment]
Thanks for providing the report and also a PR! I will have a look whether disabling the update check globally for test would also be a good option.

**Comment by georglauterbach** [comment]
Indeed, `mail_with_ldap` has not yet been adjusted to the new test helpers and the new format. This should be resolved then anyway, but I will have a look at your PR to solve this immediately :)
