### ISSUE TITLE
SASL error on upgrade to v12

### ISSUE THREAD

**Issue by zcyph** [docker-mailserver/docker-mailserver#3278]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue.
- [X] I read the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue.
- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree

### Affected Component(s)

Mail can no longer be sent

### What happened and when does this occur?

All was working fine until upgrading to version 12, and when downgrading back to 11.3.1 everything works fine again.

When I noticed I could no longer send mail after upgrading, I checked the log and found this on each failed attempt:

```
mail postfix/smtps/smtpd[1697]: warning: SASL: Connect to /var/spool/postfix/private/auth failed: No such file or directory
mail postfix/smtps/smtpd[1697]: fatal: no SASL authentication mechanisms
mail postfix/master[921]: warning: process /usr/lib/postfix/sbin/smtpd pid 1697 exit status 1
mail postfix/master[921]: warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling
```

When I do `dovecot -n` in both, I notice that this part:

```
service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = docker
    mode = 0666
    user = docker
  }
```

Was changed to:

```
service auth {
  unix_listener /dev/shm/sasl-auth.sock {
    group = postfix
    mode = 0660
    user = postfix
  }
```

Am I on the right track here? Why did this happen in moving to version 12? Any tips would be appreciated.

### What did you expect to happen?

I expected everything to continue working the same as it has in previous upgrades.

### How do we replicate the issue?

Get a working version 11 mailserver, note output of `dovecot -n`

Upgrade to version 12, repeat `dovecot -n`

### DMS version

v12.0.0

### What operating system is DMS running on?

Linux

### Which operating system version?

Ubuntu 22.04

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

**Comment by zcyph** [comment]
Adding:

```
service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = docker
    mode = 0666
    user = docker
  }
}
```
To the mounted `./docker-data/dms/config/dovecot/10-custom.conf` seems to get past the SASL error, but then sending still fails due to:

`dovecot: imap(md@privacyroot.org): Error: Couldn't load required plugin /usr/lib/dovecot/modules/lib21_fts_xapian_plugin.so: Module is for different ABI version 2.3.ABIv13(2.3.13) (we have 2.3.ABIv20(2.3.20))`

**Comment by zcyph** [comment]
Adding:

```
service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = docker
    mode = 0666
    user = docker
  }
}
```
To a mounted `./docker-data/dms/config/dovecot/10-custom.conf` seems to get past SASL error, but then still gets stuck not being able to send due to an error:

`Couldn't load required plugin /usr/lib/dovecot/modules/lib21_fts_xapian_plugin.so: Module is for different ABI version 2.3.ABIv13(2.3.13) (we have 2.3.ABIv20(2.3.20))`

**Comment by polarathene** [comment]
> To a mounted `./docker-data/dms/config/dovecot/10-custom.conf` seems to get past SASL error

This should not be necessary, unless you've been overriding this config yourself.

We changed the internal SASL socket path, this was mentioned in [our changelog](https://github.com/docker-mailserver/docker-mailserver/blob/1c9ed6ce3298a02186885a2864fd78eb18b4bd0f/CHANGELOG.md?plain=1#L78) and [release notes](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v12.0.0) but could be easy to gloss over when you've got it in your override config but not messed with it (_you try [make sure you're not out of sync elsewhere](https://github.com/docker-mailserver/docker-mailserver/blob/1c9ed6ce3298a02186885a2864fd78eb18b4bd0f/target/dovecot/10-master.conf) either_).

Your error indicates that the old path is still used in v12 for you. This is either due to you overriding that, or not re-creating the container properly (old state persisted). Not a bug, just a migration issue. You need to be a bit more careful with major versions as we introduce breaking changes like these (_although this one in particular was mostly considered internal, we won't know if third-party config changes are affected_).

---

> but then still gets stuck not being able to send due to an error:
> 
> `Couldn't load required plugin /usr/lib/dovecot/modules/lib21_fts_xapian_plugin.so: Module is for different ABI version 2.3.ABIv13(2.3.13) (we have 2.3.ABIv20(2.3.20))`

This is an issue with v12 Dovecot upgrading to community version instead of Debian package. The version apparently isn't compatible with that plugin.

You can build DMS with a build arg that will use the earlier Debian version of Dovecot if you need this plugin compatibility, and you can [track this issue](https://github.com/docker-mailserver/docker-mailserver/issues/3247#issuecomment-1504290556) for updates / discussion on resolving it.

**Comment by zcyph** [comment]
Thank you for taking the time to respond @polarathene 

I had a `/etc/postfix/main.cf` being mounted and its contents were indeed what was disagreeing with these changes. All good now.

Thank you for pointing me in the right direction.

**Comment by polarathene** [comment]
> I had a `/etc/postfix/main.cf` being mounted

You probably want to avoid that and instead mount any overrides to `/tmp/docker-mailserver/postfix-main.cf`, this will be processed during startup scripts in the container to add into `/etc/postfix/main.cf`.

If you override any other files directly, you may want to compare against our internal ones for any differences via updates you have missed since introducing them.
