### ISSUE TITLE
bug report: [ WARNING ]  Cannot find timezone 'IS'

### ISSUE THREAD

**Issue by woeisme** [docker-mailserver/docker-mailserver#3306]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue.
- [X] I read the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue.
- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree

### Affected Component(s)

no great affect

### What happened and when does this occur?

when updating to v 12 the message 
[ WARNING ]  Cannot find timezone 'IS'
appear on startup, DMS doesn't seem to recognize Iceland timezeone

### What did you expect to happen?

not to see this message

### How do we replicate the issue?

1. update server to v 12
2. docker up -d 
3. docker logs -f mailserver
4. 
5.
6.
...

### DMS version

12.0.0

### What operating system is DMS running on?

Linux

### Which operating system version?

ubuntu 22.04

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail.BLANKED
    #domainname: mail.BLANKED
    environment:
      - SSL_TYPE=letsencrypt
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
 #     - ./docker-data/acme-companion/certs/:/etc/letsencrypt/live/:ro
 #     - /home/kupo/nginxproxymanager/letsencrypt/live/npm-5:/etc/letsencrypt
 #     - /home/kupo/nginxproxymanager/letsencrypt/live/npm-5:/etc/letsencrypt/live/:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

### Relevant log output

```Text
[   INF   ]  Welcome to docker-mailserver 12.0.0
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
[   INF   ]  Starting daemons
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

**Comment by woeisme** [comment]
> TZ identifier for `IS` is [`Atlantic/Reykjavik`](https://en.wikipedia.org/wiki/Atlantic/Reykjavik).

changed it to this and error is gone, thank you.
