### ISSUE TITLE
bug report: rmdir: failed to remove '/etc/rspamd/override.d': Not a directory

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#3328]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue.
- [X] I read the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue.
- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree

### Affected Component(s)

not linking '/tmp/docker-mailserver/rspamd/override.d/'

### What happened and when does this occur?

I've just restarted DMS, and I got these warnings at startup:

> [   INF   ]  Welcome to docker-mailserver 12.1.0
> [   INF   ]  Checking configuration
> [ WARNING ]  This container was (likely) improperly restarted which can result in undefined behavior
> [ WARNING ]  Please destroy the container properly and then start DMS again
> [   INF   ]  Configuring mail server
> mv: cannot stat '/etc/cron.d/amavisd-new': No such file or directory
> rmdir: failed to remove '/etc/rspamd/override.d': Not a directory
> [ WARNING ]  (Rspamd setup) Could not remove '/etc/rspamd/override.d' (not empty?) - not linking '/tmp/docker-mailserver/rspamd/override.d/'

This only happened after the first start, after enabling Rspamd.

### What did you expect to happen?

Proper link to /tmp/docker-mailserver/rspamd/override.d/

Although, I tested going inside the container, and do:

$ cd /tmp/docker-mailserver/rspamd/override.d
$ echo "1" > test.txt

and the file was created in the mounted volume.

So the link seems to be correct.

### How do we replicate the issue?

1. Restart the container
2. Look at the docker logs

### DMS version

latest

### What operating system is DMS running on?

Linux

### Which operating system version?

CentOS 7

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker Compose

### compose.yaml

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: mailserver
    restart: always
    stop_grace_period: 1m
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS => SSL/TLS)
      - "993:993"  # IMAP4 (implicit TLS => SSL/TLS)
      - "127.0.0.1:11334:11334" # rspamd
    volumes:
      - /opt/docker/mailserver/data:/var/mail
      - /opt/docker/mailserver/state:/var/mail-state
      - /opt/docker/mailserver/logs:/var/log/mail
      - /opt/app/certificates/wildcard-domain1.com:/var/mail-ms-certs:ro
      - ./config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
      - mailserver.env
    dns:
      - 9.9.9.9
      - 8.8.8.8
      - 1.1.1.1
      - 1.0.0.1
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

**Comment by georglauterbach** [comment]
How did you restart the container?

In a fresh container, the warning does not appear.

**Comment by georglauterbach** [comment]
The error message says: `rmdir` tried to remove `/etc/rspamd/override.d` but `/etc/rspamd/override.d` is a file (or link?), and not a directory. Very strange. Why would this be a dire...


Wow. While writing it I came to a possible (likely) solution. You restarted with `stop/start` and not `down/up` (when using Compose), hence `/etc/rspamd/override.d` is still in the container as a link (which is a file in the end, not a directory). Please restart the container properly!

**Comment by ghnp5** [comment]
Ha... I used the "Restart" button in Portainer :)

Ok, fine... I'll run `docker-compose down` going forward.

Thank you!

**Comment by georglauterbach** [comment]
> I believe normal restarts should be supported. This is the only container I use that doesn't support normal restarts :)

Yes, we know. But fixing it is non-trivial I think. You're welcome to help :) This project is, in the end, maintained by people contributing in _their free time_, so there is no company in the background that supports DMS.

**Comment by ghnp5** [comment]
Absolutely! I understand!!
I don't mean to be "demanding" here 👍🏼👍🏼
Thank you very much.
