### ISSUE TITLE
bug report: Email forwarding no longer possible in v12.1 after MR #3270

### ISSUE THREAD

**Issue by JuroOravec** [docker-mailserver/docker-mailserver#3350]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read

  - the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - the [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### What operating system is the host running?

Linux

### Which operating system version?

Ubuntu 22

### What computer architecture is the host running?

AMD64 (x86_64)

### What container orchestration tool are you using?

Docker

### DMS version

v12.0

### What happened and when does this occur?

Context:

These tutorials suggest that if you create an email (using the `setup` script), and then alias it to an external email address, that you can get Docker Mailserver to forward the emails:
- https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/#using-dms-as-a-local-mail-relay-for-containers
- https://www.libe.net/en-docker-mailserver#mail-server-commissioning

However, this doesn't work anymore in v12.1. The error message (`[...] is already defined as an account`) led me to believe it's because of this change (https://github.com/docker-mailserver/docker-mailserver/pull/3270) introduced last month.

When I used mailserver version 12.0, it did work as expected - I could set up alias for an email and that way force the mailserver to forward the email. (Then I had other issues and ultimately failed trying to forward emails to my Gmail account, but that's a whole different story).

### What did you expect to happen?

Be able to use Docker Mailserver to forward incoming emails to 3rd party email address.

If there is a different (preferred) way to forward emails, I'm happy to use that. But if not and the change in https://github.com/docker-mailserver/docker-mailserver/pull/3270 broke the only option, that sounds like a bug that needs fixin'.

### Container configuration files

```yml
services:
  mailserver:
    # NOTE: Do not upgrade beyond 12.0.
    # This MR broke the option to forward email
    # https://github.com/docker-mailserver/docker-mailserver/pull/3270
    image: ghcr.io/docker-mailserver/docker-mailserver:12.0
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: system-mail.example.com
    env_file: mailserver.env
    environment:
      - RELAY_PASSWORD=${MAIL_RELAY_PASSWORD}
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./volumes/dms/mail-data/:/var/mail/
      - ./volumes/dms/mail-state/:/var/mail-state/
      - ./volumes/dms/mail-logs/:/var/log/mail/
      - ./volumes/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/certbot/conf:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### What level of experience do you have with containers, mail servers, and using a terminal?

- [ ] I am inexperienced with containers
- [X] I am rather experienced with containers
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with using a terminal (CLI)
- [X] I am rather comfortable with using a terminal (CLI)

**Comment by JuroOravec** [comment]
cc @georglauterbach @casperklein @polarathene

**Comment by georglauterbach** [comment]
Have you tried https://github.com/docker-mailserver/docker-mailserver/issues/3262#issuecomment-1509366419?

**Comment by georglauterbach** [comment]
But nice reminder to myself that this section of our docs need an update.

**Comment by polarathene** [comment]
A [later comment by me in that same discussion](https://github.com/docker-mailserver/docker-mailserver/issues/3262#issuecomment-1547041446) also explains a way to workaround it.

This is not something we meant to support because I'm not sure that we can support everyones expectations/assumptions. Especially when there are many accounts to forward, or an entire wildcard.

## Help justify why alternative options aren't as good

Normally it's assumed if you're aliasing mail to a different recipient address, then the alias itself is not an address you'd send mail from (_since inbound and outbound mail will resolve the alias of the recipient first_). It's acting as a filter or redirect.

Most complaints we have received due to this change is from users with gmail accounts that have multiple aliases in DMS resolve to a single gmail address. They then use Gmail for the web/mobile UI to manage their mail. Presumably you send from Gmail as well via DMS port 587 / 465?

Any reason ThunderBird, RoundCube or similar aren't options? They integrate better AFAIK. I've provided some alternatives below that may still work for Gmail. Understandably they're probably not as simple.

If more users chime in, it may warrant some way to support this specific use-case, or some opt-in flag/ENV that acknowledges enabling such may be at risk of bugs / compatibility issues that won't be supported by maintainers.

## Overview

Generally, you would have this kind of setup:
- Inbound ail arrives at DMS and is stored locally for accounts managed by Dovecot, or relayed externally. Mail client (ThunderBird, Webmail UI/service) accesses mail from DMS via IMAP or POP3.
- Outbound mail is submitted to DMS to send to a recipient directly or via relay service (like SendGrid). Mail clients connect to DMS over ports 465 or 587 to submit mail via authenticated account.
- Virtual aliases should resolve the recipient first. If that recipient then belongs to an account in `mydestination` or one of the accounts Dovecot manages, then it should be delivered there. Otherwise outbound delivery may be attempted (_authenticated accounts without `SPOOF_PROTECTION=1` enabled for DMS should be able to send mail out as any address, legitimate ownership or not_).
- DMS could be configured as a null client (only sends mail, never receives it)
- DMS could be configured only to receive mail, never send it.
- DMS could be configured to only relay mail, never store it. (**your preference**)

Related features with no support for multiple addresses to a single address (_although Postfix has various config to rewrite a sender or recipient address_):
- `relay_host` => Outbound mail is relayed through another service. If DMS is authorized to receive mail for an address but not store it locally, it will attempt to relay. You can selectively use relays for a domain or specific addresses.
- `relay_domains` (_manual `postfix-main.cf` config support via DMS only at present_) => Mail for this domain (or specific recipients arrives to DMS and is relayed to another mail server instead of being stored in Dovecot.
- `transport_maps` (_likewise, no official DMS support at present, manual config via `postfix-main.cf` only_) => Mail for a domain or specific addresses can be redirected to a non-standard transport. Useful if it needs configuration / behaviour to differ, such as a discard for a `noreply@` address.

## Alternative - Multiple DMS

I suppose you could have two instances of DMS as a workaround. One that receives mail on port 25 and relays it to the external mail server. Another that lets you login over port 587 or 465 and is send-only, so long as you don't try to send mail to another address for that domain.

Or manage the accounts/aliases config files manually like the referenced comment explains. You could probably also use `user-patches.sh` to patch out the guard we've added in 12.1 that prevents the mail account / alias overlap. But it doesn't seem like a good idea for DMS to think the address belongs locally and externally?

---

## Alternative - POP3

For the POP3 issue with catch-all domain or many accounts, since preserving the recipient may not matter, I think it's possible to have mail delivered from multiple addresses / catch-all to a single mailbox. There is [this feature request](https://github.com/docker-mailserver/docker-mailserver/issues/3022) to support that in DMS.

Sending shouldn't matter. As mentioned, just have an account to authenticate as, and you can send as whatever address you like without `SPOOF_PROTECTION=1`. Technically the account doesn't have to belong to a real domain IIRC, you connect to DMS which has nothing to do with the domain part of the login (_which also technically isn't required, it's just what the account "username" is created as for Dovecot_).

Perhaps try `setup email add hello@example.test not-secure-password`. You should be able to login to that, and `.test` is a reserved TLD, so no there will be no public DNS resolving to the domain if I'm mistaken and something tries to send mail back. Just set the sender address to something different in the mail client.

Don't use your `@gmail.com` or similar though. Users have done this in the past and it tells DMS that the domain is managed by DMS, so mail sent to any gmail account then attempts to deliver locally and rejects it because no account exists.

---

## Alternative - Login via alias (won't work with only a catch-all / wildcard)

Virtual aliases (`postfix-virtual.cf` / `setup alias add ...`) are good for forwarding mail. I believe we also by default (due to `DOVECOT_QUOTAS=1`) have a workaround that creates dummy Dovecot accounts for aliases (assuming you have more than a wildcard). These can apparently login and send mail as a result, which may prevent you from the need to create a real mailbox account.

I wouldn't rely on that to stick around, but I'm also not aware of anyone replacing this workaround with a proper fix (_requires a policy service for Postfix to be written that resolves aliases to Dovecot accounts to query the quota usage, since Postfix doesn't do this and just queries aliases for quota from non-existent accounts otherwise, hence the dummy accounts_).

**Comment by georglauterbach** [comment]
We should definitely update our docs with this information. @polarathene do you want me to do that (I'd copy some of your text into the docs).

**Comment by polarathene** [comment]
> We should definitely update our docs with this information.

:+1: 

> @polarathene do you want me to do that (I'd copy some of your text into the docs).

Yeah sorry, I am trying not to take on anymore tasks until I finish up the current ones. Dealing with upstream `moby`/`containerd` atm :sweat_smile: 

I think the main use-case we see complaints for is forwarding multiple addresses (or entire wildcard) to a single address at another mail server like Gmail (pretty much always gmail).

I am assuming gmail is more convenient than using ThunderBird, or additionally hosting a webmail service like RoundCube. Since it appears it's only being used to receive the mail and relay through DMS.

With the main issue being adding a mail account to send mail out via DMS, you probably only have to clear up that misunderstanding of `setup email add ...` not having to match the same address as who you want to send as. Should include an admonition about `SPOOF_PROTECTION=1`, or link to docs page about how to allow sending as other accounts.
