### ISSUE TITLE
bug report: I'm having issues with SASL even though I don't use it

### ISSUE THREAD

**Issue by fabriciomrtnz** [docker-mailserver/docker-mailserver#3376]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read

  - the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - the [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### What operating system is the host running?

Linux

### Which operating system version?

armbian 23.02 Bullseye

### What computer architecture is the host running?

ARM64 (AArch64)

### What container orchestration tool are you using?

Kubernetes (not officially supported)

### DMS version

v12.1.0

### What happened and when does this occur?

I am trying to upgrade from version 11 and I'm getting SASL errors when I attempt to send mail.

### What did you expect to happen?

My current configurations works in version 11.2

### Container configuration files

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
  namespace: www
  labels:
    app: mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
      - name: mailserver
#        image: docker.io/mailserver/docker-mailserver:11.2.0
        image: docker.io/mailserver/docker-mailserver:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: TZ
          value: "Europe/Madrid"
        - name: OVERRIDE_HOSTNAME
          value: "mail.inomba.com"
        - name: LOG_LEVEL
          value: "info"
        - name: DOMAINNAME
          value: "inomba.com"
        - name: DMS_DEBUG
          value: "1"
        - name: SUPERVISOR_LOGLEVEL
          value: "info"
        - name: ONE_DIR
          value: "1"
        - name: ACCOUNT_PROVISIONER
          value: "FILE"
        - name: ENABLE_DNSBL
          value: "1"
        - name: POSTMASTER_ADDRESS
          value: "postmaster@inomba.com"
        - name: ENABLE_SRS
          value: "1"
        - name: ENABLE_POP3
          value: "1"
        - name: ENABLE_CLAMAV
          value: "1"
        - name: ENABLE_FAIL2BAN
          value: "0"
        - name: SMTP_ONLY
          value: "0"
        - name: ENABLE_MANAGESIEVE
          value: "1"
        - name: POSTSCREEN_ACTION
          value: "enforce"
        - name: SSL_TYPE
          value: "manual"
        - name: SSL_KEY_PATH
          value: "/etc/certs/inomba.com/privkey.pem"
        - name: SSL_CERT_PATH
          value: "/etc/certs/inomba.com/fullchain.pem"
        - name: TLS_LEVEL
          value: "modern"
        - name: PFLOGSUMM_TRIGGER
          value: "logrotate"
        - name: PFLOGSUMM_RECIPIENT
          value: "fmartinez@inomba.com"
        - name: PFLOGSUMM_SENDER
          value: "postmaster@inomba.com"
        - name: LOGWATCH_INTERVAL
          value: "weekly"
        - name: LOGWATCH_RECIPIENT
          value: "fmartinez@inomba.com"
        - name: REPORT_RECIPIENT
          value: "0"
        - name: REPORT_SENDER
          value: "postmaster@inomba.com"
        - name: REPORT_INTERVAL
          value: "monthly"
        - name: POSTFIX_INET_PROTOCOLS
          value: "ipv4"
        - name: DOVECOT_INET_PROTOCOLS
          value: "ipv4"
        - name: ENABLE_SPAMASSASSIN
          value: "1"
        - name: SPAMASSASSIN_SPAM_TO_INBOX
          value: "1"
        - name: MOVE_SPAM_TO_JUNK
          value: "1"
        - name: SA_TAG
          value: "2.0"
        - name: SA_TAG2
          value: "6.31"
        - name: SA_KILL
          value: "6.31"
        - name: SA_SPAM_SUBJECT
          value: "*****SPAM*****"
        - name: ENABLE_FETCHMAIL
          value: "0"
        - name: ENABLE_LDAP
          value: "0"
        - name: DOVECOT_TLS
          value: "yes"
        - name: DOVECOT_MAILBOX_FORMAT
          value: "maildir"
        - name: ENABLE_POSTGREY
          value: "1"
        - name: POSTGREY_DELAY
          value: "300"
        - name: POSTGREY_MAX_AGE
          value: "35"
        - name: POSTGREY_TEXT
          value: "Delayed by Postgrey"
        - name: POSTGREY_AUTO_WHITELIST_CLIENTS
          value: "5"
        - name: SRS_SENDER_CLASSES
          value: "envelope_sender"
        - name: DEFAULT_RELAY_HOST
          value: "[smtp.mailgun.org]:587"
        - name: RELAY_HOST
          value: "smtp.mailgun.org"
        - name: POSTFIX_MESSAGE_SIZE_LIMIT
          value: "100000000"
        - name: ENABLE_RSPAMD
          value: "1"
        - name: RSPAMD_GREYLISTING
          value: "1"
        - name: RSPAMD_LEARN
          value: "1"
        - name: RSPAMD_HFILTER
          value: "1"
        ports:
        - containerPort: 25
          name: smtp
          protocol: TCP
        - containerPort: 587
          name: msa
          protocol: TCP
        - containerPort: 143
          name: imap
          protocol: TCP
        - containerPort: 465
          name: smtps
          protocol: TCP
        - containerPort: 993
          name: imaps
          protocol: TCP
        - containerPort: 110
          name: pop3
          protocol: TCP
        - containerPort: 995
          name: pop3s
          protocol: TCP
        - containerPort: 4190
          name: sieve
          protocol: TCP
        volumeMounts:
        - name: resources
          mountPath: /tmp/
          subPath: config/
        - name: resources
          mountPath: /var/log/
          subPath: log/
        - name: resources
          mountPath: /etc/dovecot/
          subPath: etc/dovecot/
        - name: resources
          mountPath: /etc/certs/
          subPath: keys/
        - name: resources
          mountPath: /var/mail/
          subPath: mailboxes/
        - name: resources
          mountPath: /etc/postfix-policyd-spf-python/policyd-spf.conf
          subPath: config/docker-mailserver/postfix-policyd-spf.conf
        - name: resources
          mountPath: /etc/cron.d/sa-learn
          subPath: etc/cron.d/sa-learn
        - name: resources
          mountPath: /var/mail-state
          subPath: mail-state/
      volumes:
      - name: resources
        persistentVolumeClaim:
          claimName: mailserver
```

### Relevant log output

```Text
May 28 23:21:36 mailserver-5768b9779d-mngmt dovecot: imap-login: Login: user=<fmartinez@iseguro.com>, method=PLAIN, rip=10.42.0.1, lip=10.42.0.210, mpid=1297, TLS, session=<pgIWjsf8WEQKKgAB>
May 28 23:21:36 mailserver-5768b9779d-mngmt dovecot: imap-login: Login: user=<fmartinez@inomba.com>, method=PLAIN, rip=10.42.0.1, lip=10.42.0.210, mpid=1298, TLS, session=<hDwWjsf8iHAKKgAB>
May 28 23:21:58 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1332]: connect from unknown[10.42.0.1]
May 28 23:21:58 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1332]: Anonymous TLS connection established from unknown[10.42.0.1]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
May 28 23:21:58 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1332]: warning: SASL: Connect to /dev/shm/sasl-auth.sock failed: No such file or directory
May 28 23:21:58 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1332]: fatal: no SASL authentication mechanisms
May 28 23:21:59 mailserver-5768b9779d-mngmt postfix/master[1083]: warning: process /usr/lib/postfix/sbin/smtpd pid 1332 exit status 1
May 28 23:21:59 mailserver-5768b9779d-mngmt postfix/master[1083]: warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling
May 28 23:22:59 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1425]: connect from unknown[10.42.0.1]
May 28 23:23:00 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1425]: SSL_accept error from unknown[10.42.0.1]: Broken pipe
May 28 23:23:00 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1425]: lost connection after CONNECT from unknown[10.42.0.1]
May 28 23:23:00 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1425]: disconnect from unknown[10.42.0.1] commands=0/0
May 28 23:23:00 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1425]: connect from unknown[10.42.0.1]
May 28 23:28:00 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1425]: SSL_accept error from unknown[10.42.0.1]: Connection timed out
May 28 23:28:00 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1425]: lost connection after CONNECT from unknown[10.42.0.1]
May 28 23:28:00 mailserver-5768b9779d-mngmt postfix/smtps/smtpd[1425]: disconnect from unknown[10.42.0.1] commands=0/0
```

### What level of experience do you have with containers, mail servers, and using a terminal?

- [ ] I am inexperienced with containers
- [X] I am rather experienced with containers
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with using a terminal (CLI)
- [X] I am rather comfortable with using a terminal (CLI)

**Comment by polarathene** [comment]
Looks like you closed this before I got back to respond :sweat_smile: (response below for anyone that lands here... oh you just deleted your original comment... ok then.

---

Defaults are to use Dovecot for account management, this uses SASL implicitly. We support alternative SASL auth implementations for those that don't want Dovecot to manage accounts.

```
postfix/smtps/smtpd[1332]: warning: SASL: Connect to /dev/shm/sasl-auth.sock failed: No such file or directory
postfix/smtps/smtpd[1332]: fatal: no SASL authentication mechanisms
```

> I searched the issue tracker but was unable to find my issue.

:thinking: https://github.com/docker-mailserver/docker-mailserver/issues/3278#issuecomment-1518899333

**Comment by fabriciomrtnz** [comment]
My problem was based on that I needed to modify /etc/dovecot/ and had a config mounted that did not work with updated version.
