### ISSUE TITLE
[TODO]: `SMTP_ONLY=1` feature should swap `virtual_mailbox_domains` with `virtual_alias_domains`

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#4142]
### Subject

Something else that requires developers attention

### Description

Documenting here as I'm a bit busy and will probably forget this information otherwise.

---

The primary task is a bug fix for `SMTP_ONLY=1`, it just needs to adjust `/etc/postfix/main.cf` to reflect:

```
virtual_alias_domains=/etc/postfix/vhost
# Set to emtpy/blank. Removing will fallback to `$virtual_mailbox_maps` (might be ok?):
virtual_mailbox_domains=
```

I am going to be switch to higher priority tasks, but:
- The above is simple enough if someone wants to contribute it, otherwise use `postfix-main.cf` support to DIY locally.
- Other tasks related to this are effectively documentation updates.

---

During a [recent investigation](https://github.com/docker-mailserver/docker-mailserver/issues/4133#issuecomment-2254107563) it was discovered that the `SMTP_ONLY=1` feature is a bit error prone when it receives mail for a recipient that is not to be forwarded externally, the most likely scenario is the recipient does not exist.

The fix is for `SMTP_ONLY=1` to use `virtual_alias_domains = /etc/postfix/vhost` instead of the default `virtual_mailbox_domains = /etc/postfix/vhost`. Presently this is handled in our default `main.cf`:

https://github.com/docker-mailserver/docker-mailserver/blob/01194b7552ec974da58b691c1ee2e238de87333b/target/postfix/main.cf#L102-L106

The two settings cannot overlap in domains (_similar to how this file should not have domains that exist in `main.cf:mydestination` setting_), the domains assigned must be exclusive to the setting:
- If neither are configured, then Postfix will reject mail for alias recipients since there is no intended local mailbox storage to deliver internally to, it is seen as a request to relay to the external recipient address resolved by an alias (if one exists).
- Only trusted clients (`PERMIT_DOCKER` ENV) or authenticated submission via ports 587/465 will allow accepting mail to be relayed if Postfix does not recognize the domain as managed.
- See the "VIRTUAL ALIAS DOMAINS" section of the [`virtual(5)` Postfix docs](https://www.postfix.org/virtual.5.html) for distinction between virtual aliases and virtual mailboxes.

I've not considered any other contexts. The test suite is not yet capable of matrix testing variations with `SMTP_ONLY=1`, nor the current community approaches that add users that Postfix can accept for authenticated submission. So there is potential this may introduce a regression for other `SMTP_ONLY=1` deployments, but it's presumed unlikely.

The upstream default for [`virtual_alias_domains`](https://www.postfix.org/postconf.5.html#virtual_alias_domains) (and `virtual_mailbox_domains`) is to use their `_maps` equivalent as linked upstream docs show. For us this is `postfix-virtual.cf` processed into `/etc/postfix/virtual` file, but the format would not have entries that `_domains` expects.. which is why no conflicts/overlap concerns have occurred in existing DMS releases.

---

## Tasks

Fairly easy fix to contribute scripts wise. There is some related tasks that could be tackled, but these are only complimentary, not required for addressing the actual issue 👍 

- [ ] Add fix to scripts for `SMTP_ONLY=1` as described above, fairly simple.
- [ ] Add to the repo examples folder a revised version of the `compose.yaml` from: https://github.com/docker-mailserver/docker-mailserver/issues/4133#issuecomment-2259617725
- [ ] [This docs page on a forwarding server](https://docker-mailserver.github.io/docker-mailserver/v14.0/examples/use-cases/forward-only-mailserver-with-ldap-authentication/#building-a-forward-only-mail-server) should probably be updated/rewritten to reference the `compose.yaml` example for troubleshooting and what the equivalent production `compose.yaml` would look like (_much simpler_).
  - LDAP is used for accounts to support mail submission too it seems, but so is `PERMIT_DOCKER` ENV, seems to be mixed use-case that could be better distinguished.
  - `SMTP_ONLY=1` may get alternative account provisioning support: https://github.com/docker-mailserver/docker-mailserver/issues/3477
  - If the LDAP config is relevant it'll need to be revised for v15 release of DMS due to refactoring of the LDAP provisioner support.
- [ ] Other doc content for `SMTP_ONLY=1` should probably be considered:
  - [FAQ entry on authentication support](https://docker-mailserver.github.io/docker-mailserver/v14.0/faq/#how-can-i-authenticate-users-with-smtp_only1)
  - [`SMTP_ONLY=1` ENV docs](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/environment/#smtp_only)

Priority is considered low due to this feature not impacting the majority of DMS users and simple workarounds. If there are more reports related to the issue, they can be directed to [this workaround solution](https://github.com/docker-mailserver/docker-mailserver/issues/4133#issuecomment-2259617725) with `postfix-main.cf`, related docs could also link to that as an interim fix.
