### ISSUE TITLE
[TODO]: Small tasks

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#4148]
### Subject

I would like to contribute to the project

### Description

Some small tasks that shouldn't require much time / effort individually if anyone wants to tackle them:

**Docs:**
- [ ] Check docs for any existing mention of client access restriction. If nothing to update, [this discussion](https://github.com/orgs/docker-mailserver/discussions/3847) may be worth adding a FAQ link to.
- [ ] The v14.1 docs have a [`dovecot-solr` example with `compose.yaml` snippet](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/dovecot-solr/#composeyaml) that demonstrates how to easily extend DMS without extra files. Some users aren't aware of this useful feature, could be good to raise awareness?
  - [ ] Might be worth adding as a subsection to the [build DMS image](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/docker-build/) page, or a separate complimentary page for extending the image.
  - [ ] Another good location is the [`demo-setups`](https://github.com/docker-mailserver/docker-mailserver/tree/a338c0663931d621105b42350e44608ffc8abf13/demo-setups) repo folder. Including a `compose.yaml` there is simple copy/paste (_with either link reference to the docs, or `git blame` the `dovecot-solr` page PR for an issue comment link for context?_)

**Scripts:**
- [ ] **Not important to fix** - `SMTP_ONLY=1` (_and likely `ACCOUNT_PROVISIONER=LDAP`?_) don't actually support the current DMS default of `ENABLE_QUOTAS=1`.
  - `setup email list` is for `postfix-accounts.cf`, which should rarely exist with either of those ENV settings.
  - The list command will fail to query quota since Dovecot would not have been configured with the feature, triggering [this call](https://github.com/docker-mailserver/docker-mailserver/blob/a338c0663931d621105b42350e44608ffc8abf13/target/bin/listmailuser#L35-L36) to error/fail [here](https://github.com/docker-mailserver/docker-mailserver/blob/a338c0663931d621105b42350e44608ffc8abf13/target/bin/listmailuser#L59-L60).
